name = "lean-pool"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanPool"]
requiresModuleSystem = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "TauCeti"
git = "https://github.com/TauCetiProject/TauCeti"
rev = "5189e8a380bdf5740cc1fe4123cc9cbe635724c2"

# Keep Mathlib last so its transitive dependency pins take precedence.
[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc3"

[[lean_lib]]
name = "LeanPool"
globs = ["LeanPool.*"]

[[lean_exe]]
name = "mk_all"
root = "ProjectIndexes"
srcDir = "scripts"
