/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import Mathlib.GroupTheory.HNNExtension

/-! ## Transporting HNN extensions across an equivalence of HNN data -/

@[expose] public section

open Set

namespace Undecidability
namespace HNNLemmas

variable {G : Type*} [Group G]
variable {A B : Subgroup G} {phi : A ≃* B}

/-- An injective homomorphism identifies its domain with its range. -/
noncomputable def equivRangeOfInjective
    {H : Type*} [Group H] (f : H →* G) (hf : Function.Injective f) :
    H ≃* MonoidHom.range f :=
  MulEquiv.ofBijective f.rangeRestrict
    ⟨MonoidHom.rangeRestrict_injective_iff.mpr hf,
      f.rangeRestrict_surjective⟩

/-- Two injectively parametrized subgroups with the same parameter group are
canonically isomorphic. -/
noncomputable def rangeEquiv
    {H : Type*} [Group H] (f g : H →* G)
    (hf : Function.Injective f) (hg : Function.Injective g) :
    MonoidHom.range f ≃* MonoidHom.range g :=
  (equivRangeOfInjective f hf).symm.trans (equivRangeOfInjective g hg)

@[simp]
theorem rangeEquiv_apply_range
    {H : Type*} [Group H] (f g : H →* G)
    (hf : Function.Injective f) (hg : Function.Injective g) (x : H) :
    ((rangeEquiv f g hf hg ⟨f x, ⟨x, rfl⟩⟩ : MonoidHom.range g) : G) =
      g x := by
  change g ((equivRangeOfInjective f hf).symm ⟨f x, ⟨x, rfl⟩⟩) = g x
  have hy : (equivRangeOfInjective f hf).symm ⟨f x, ⟨x, rfl⟩⟩ = x := by
    apply hf
    exact congrArg Subtype.val
      ((equivRangeOfInjective f hf).apply_symm_apply ⟨f x, ⟨x, rfl⟩⟩)
  exact congrArg g hy

/-- The subgroup generated by an embedded subgroup and the stable letter. -/
def generatedWithStable (H : Subgroup G) :
    Subgroup (HNNExtension G A B phi) :=
  Subgroup.closure
    ((↑(H.map (HNNExtension.of (A := A) (B := B) (φ := phi))) :
        Set (HNNExtension G A B phi)) ∪
      {HNNExtension.t (A := A) (B := B) (φ := phi)})

/-- A homomorphism between HNN extensions induced by equivalences of the
base groups and both associated subgroups.  The three compatibility
hypotheses say that the subgroup equivalences are the restrictions of the
base equivalence and intertwine the attaching maps. -/
def congrHom
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    HNNExtension G A B phi →* HNNExtension G' A' B' φ' :=
  HNNExtension.lift
    ((HNNExtension.of (A := A') (B := B') (φ := φ')).comp e.toMonoidHom)
    (HNNExtension.t (A := A') (B := B') (φ := φ')) (by
      intro a
      have ht := HNNExtension.t_mul_of (φ := φ') (eA a)
      change
        HNNExtension.t * HNNExtension.of (e (a : G)) =
          HNNExtension.of (e (phi a : G)) * HNNExtension.t
      rw [← hA a, ← hB (phi a)]
      simpa [hφ a] using ht)

@[simp]
theorem congrHom_of
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) (g : G) :
    congrHom e eA eB hA hB hφ
        (HNNExtension.of (A := A) (B := B) (φ := phi) g) =
      HNNExtension.of (A := A') (B := B') (φ := φ') (e g) := by
  simp [congrHom]

@[simp]
theorem congrHom_t
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    congrHom e eA eB hA hB hφ
        (HNNExtension.t (A := A) (B := B) (φ := phi)) =
      HNNExtension.t (A := A') (B := B') (φ := φ') := by
  simp [congrHom]

/-- Isomorphic HNN data give isomorphic HNN extensions, with the stable
letter fixed. -/
noncomputable def congr
    {G' : Type*} [Group G'] {A' B' : Subgroup G'} {φ' : A' ≃* B'}
    (e : G ≃* G') (eA : A ≃* A') (eB : B ≃* B')
    (hA : ∀ a : A, (eA a : G') = e (a : G))
    (hB : ∀ b : B, (eB b : G') = e (b : G))
    (hφ : ∀ a : A, eB (phi a) = φ' (eA a)) :
    HNNExtension G A B phi ≃* HNNExtension G' A' B' φ' := by
  let hA' : ∀ a' : A', (eA.symm a' : G) = e.symm (a' : G') := by
    intro a'
    apply e.injective
    rw [e.apply_symm_apply, ← hA (eA.symm a'), eA.apply_symm_apply]
  let hB' : ∀ b' : B', (eB.symm b' : G) = e.symm (b' : G') := by
    intro b'
    apply e.injective
    rw [e.apply_symm_apply, ← hB (eB.symm b'), eB.apply_symm_apply]
  let hφ' : ∀ a' : A', eB.symm (φ' a') = phi (eA.symm a') := by
    intro a'
    apply eB.injective
    rw [eB.apply_symm_apply, hφ (eA.symm a'), eA.apply_symm_apply]
  let f := congrHom e eA eB hA hB hφ
  let g := congrHom e.symm eA.symm eB.symm hA' hB' hφ'
  refine
    { toFun := f
      invFun := g
      left_inv := ?_
      right_inv := ?_
      map_mul' := map_mul f }
  · intro x
    have hgf : g.comp f = MonoidHom.id _ := by
      apply HNNExtension.hom_ext
      · ext z
        simp [f, g]
      · simp [f, g]
    exact DFunLike.congr_fun hgf x
  · intro x
    have hfg : f.comp g = MonoidHom.id _ := by
      apply HNNExtension.hom_ext
      · ext z
        simp [f, g]
      · simp [f, g]
    exact DFunLike.congr_fun hfg x

/-!
The first intersection calculation is most conveniently proved by comparing
the ambient HNN extension with the HNN extension obtained by restricting both
associated subgroups to `H`.  The following definitions and lemmas implement
that comparison.  The construction and its basic API are public because the
same restricted embedding is also used to prove exact subgroup presentations
at later HNN stages; only the normal-form implementation remains private.
-/

/-- Restrict the first associated subgroup to a base subgroup. -/
def restrictedA (H : Subgroup G) : Subgroup H :=
  A.comap H.subtype

/-- Restrict the second associated subgroup to a base subgroup. -/
def restrictedB (H : Subgroup G) : Subgroup H :=
  B.comap H.subtype

/-- The associated-subgroup isomorphism restricted to a compatible base subgroup. -/
def restrictedPhi (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    restrictedA (A := A) H ≃* restrictedB (B := B) H where
  toFun a :=
    ⟨⟨phi ⟨((a : H) : G), a.property⟩,
        (hphi ⟨((a : H) : G), a.property⟩).mp (a : H).property⟩,
      (phi ⟨((a : H) : G), a.property⟩).property⟩
  invFun b :=
    let bb : B := ⟨((b : H) : G), b.property⟩
    let aa : A := phi.symm bb
    ⟨⟨(aa : G), (hphi aa).mpr (by simp [bb, aa, (b : H).property])⟩,
      aa.property⟩
  left_inv a := by
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun x : A ↦ (x : G)) (phi.symm_apply_apply ⟨((a : H) : G), a.property⟩)
  right_inv b := by
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun x : B ↦ (x : G)) (phi.apply_symm_apply ⟨((b : H) : G), b.property⟩)
  map_mul' a b := by
    refine Subtype.ext (Subtype.ext ?_)
    change
      (phi
          (⟨((a : H) : G) * ((b : H) : G),
            A.mul_mem a.property b.property⟩ : A) : G) = _
    let aa : A := ⟨((a : H) : G), a.property⟩
    let bb : A := ⟨((b : H) : G), b.property⟩
    exact congrArg (fun x : B ↦ (x : G)) (map_mul phi aa bb)

/-- The induced homomorphism from the restricted HNN extension into the original extension. -/
def restrictedEmbedding (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
        (restrictedPhi H hphi) →*
      HNNExtension G A B phi :=
  HNNExtension.lift
    ((HNNExtension.of (A := A) (B := B) (φ := phi)).comp H.subtype)
    (HNNExtension.t (A := A) (B := B) (φ := phi)) (by
      intro a
      change HNNExtension.t * HNNExtension.of (((a : H) : G)) =
        HNNExtension.of
            ((((restrictedPhi H hphi) a : restrictedB (B := B) H) : H) : G) *
          HNNExtension.t
      simpa [restrictedPhi] using HNNExtension.t_mul_of
        (φ := phi) (⟨((a : H) : G), a.property⟩ : A))

@[simp]
theorem restrictedEmbedding_of (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) (h : H) :
    restrictedEmbedding H hphi (HNNExtension.of h) =
      HNNExtension.of (h : G) := by
  simp [restrictedEmbedding]

@[simp]
theorem restrictedEmbedding_t (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    restrictedEmbedding H hphi HNNExtension.t = HNNExtension.t := by
  simp [restrictedEmbedding]

theorem restrictedEmbedding_range (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    MonoidHom.range (restrictedEmbedding H hphi) =
      generatedWithStable (A := A) (B := B) (phi := phi) H := by
  apply le_antisymm
  · rintro x ⟨y, rfl⟩
    induction y using HNNExtension.induction_on with
    | of h =>
        apply Subgroup.subset_closure
        left
        exact ⟨h, h.property, by simp⟩
    | t =>
        apply Subgroup.subset_closure
        exact Or.inr (Set.mem_singleton _)
    | mul x y hx hy => simpa using Subgroup.mul_mem _ hx hy
    | inv x hx => simpa using Subgroup.inv_mem _ hx
  · unfold generatedWithStable
    rw [Subgroup.closure_le]
    rintro x (hx | rfl)
    · rcases hx with ⟨h, hh, rfl⟩
      exact ⟨HNNExtension.of (⟨h, hh⟩ : H), by simp⟩
    · exact ⟨HNNExtension.t, by simp⟩

private lemma mem_restricted_toSubgroup (H : Subgroup G) (u : ℤˣ) (h : H)
    (hh : (h : G) ∈ HNNExtension.toSubgroup A B u) :
    h ∈ HNNExtension.toSubgroup
      (restrictedA (A := A) H) (restrictedB (B := B) H) u := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · change ((h : G) ∈ A)
    simpa using hh
  · change ((h : G) ∈ B)
    simpa using hh

/-- Carry a reduced word of the restricted HNN extension into the original base group. -/
def mapRestrictedReducedWord (H : Subgroup G)
    (w : HNNExtension.NormalWord.ReducedWord H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :
    HNNExtension.NormalWord.ReducedWord G A B where
  head := (w.head : G)
  toList := w.toList.map (fun x ↦ (x.1, (x.2 : G)))
  chain := by
    rw [List.isChain_map]
    apply w.chain.imp
    intro a b hab hmem
    exact hab (mem_restricted_toSubgroup H a.1 a.2 hmem)

private lemma mapRestrictedReducedWord_prod (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (w : HNNExtension.NormalWord.ReducedWord H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :
    (mapRestrictedReducedWord (A := A) (B := B) H w).prod phi =
      restrictedEmbedding H hphi (w.prod (restrictedPhi H hphi)) := by
  simp only [HNNExtension.NormalWord.ReducedWord.prod,
    mapRestrictedReducedWord, List.map_map, map_mul, map_list_prod]
  congr 1
  induction w.toList with
  | nil => simp
  | cons x xs ih =>
      simp only [List.map_cons, List.prod_cons, ih]
      simp [restrictedEmbedding]

private theorem restrictedEmbedding_preimage_base (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (y : HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
      (restrictedPhi H hphi))
    (hy : restrictedEmbedding H hphi y ∈
      MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi))) :
    ∃ h : H, y = HNNExtension.of h := by
  let psi := restrictedPhi H hphi
  let : Nonempty (HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H) :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv psi d) y
  have hwy : w.toReducedWord.prod psi = y :=
    (HNNExtension.NormalWord.equiv psi d).symm_apply_apply y
  have hmapped :
      (mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord).prod phi ∈
        MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
    rw [mapRestrictedReducedWord_prod H hphi, hwy]
    exact hy
  have hnilmap :=
    HNNExtension.ReducedWord.toList_eq_nil_of_mem_of_range phi
      (mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord) hmapped
  have hnil : w.toList = [] := by
    simpa [mapRestrictedReducedWord] using hnilmap
  refine ⟨w.head, ?_⟩
  rw [← hwy]
  simp [HNNExtension.NormalWord.ReducedWord.prod, hnil]

/-- The canonical homomorphism from an HNN extension restricted to a
subgroup `H` into the ambient HNN extension is injective.  This is the
injectivity assertion in the restricted-HNN lemma: a non-base reduced word
remains reduced in the ambient extension, while injectivity on the base is
`HNNExtension.of_injective`. -/
theorem restrictedEmbedding_injective (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    Function.Injective (restrictedEmbedding H hphi) := by
  apply (injective_iff_map_eq_one (restrictedEmbedding H hphi)).mpr
  intro y hy
  have hybase : restrictedEmbedding H hphi y ∈
      MonoidHom.range
        (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
    refine ⟨1, ?_⟩
    simpa using hy.symm
  rcases restrictedEmbedding_preimage_base H hphi y hybase with ⟨h, rfl⟩
  rw [restrictedEmbedding_of] at hy
  have hh : (h : G) = 1 := by
    apply HNNExtension.of_injective phi
    simpa using hy
  have hH : h = 1 := by
    apply Subtype.ext
    exact hh
  simp [hH]

/-- The restricted HNN extension, identified with the subgroup generated by
the embedded copy of `H` and the ambient stable letter.  This is the exact
subgroup-presentation form of Lemma B.2 of the paper used by the compression
stages. -/
noncomputable def restrictedEquivGeneratedWithStable (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    HNNExtension H (restrictedA (A := A) H) (restrictedB (B := B) H)
        (restrictedPhi H hphi) ≃*
      generatedWithStable (A := A) (B := B) (phi := phi) H :=
  (MonoidHom.ofInjective (restrictedEmbedding_injective H hphi)).trans
    (MulEquiv.subgroupCongr (restrictedEmbedding_range H hphi))

@[simp]
theorem restrictedEquivGeneratedWithStable_coe (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    (x : HNNExtension H (restrictedA (A := A) H)
      (restrictedB (B := B) H) (restrictedPhi H hphi)) :
    ((restrictedEquivGeneratedWithStable H hphi x :
        generatedWithStable (A := A) (B := B) (phi := phi) H) :
      HNNExtension G A B phi) = restrictedEmbedding H hphi x := by
  simp [restrictedEquivGeneratedWithStable,
    MonoidHom.ofInjective_apply, MulEquiv.subgroupCongr_apply]

/--
Restricted-HNN intersection lemma (Lemma B.2 of the paper), stated in the
form used by the tower calculations.
-/
theorem generatedWithStable_inf_base
    (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H) :
    generatedWithStable (A := A) (B := B) (phi := phi) H ⊓
        MonoidHom.range (HNNExtension.of (A := A) (B := B) (φ := phi)) =
      H.map (HNNExtension.of (A := A) (B := B) (φ := phi)) := by
  ext x
  constructor
  · intro hx
    have hxg : x ∈ generatedWithStable (A := A) (B := B) (phi := phi) H := hx.1
    rw [← restrictedEmbedding_range H hphi] at hxg
    rcases hxg with ⟨y, hy⟩
    rcases restrictedEmbedding_preimage_base H hphi y (hy ▸ hx.2) with ⟨h, rfl⟩
    rw [restrictedEmbedding_of] at hy
    exact ⟨h, h.property, hy⟩
  · rintro ⟨g, hg, rfl⟩
    constructor
    · apply Subgroup.subset_closure
      exact Or.inl ⟨g, hg, rfl⟩
    · exact ⟨g, rfl⟩

/-- Every element of the subgroup generated by an embedded subgroup `H` and
the stable letter admits an ambient HNN-reduced word all of whose base
coefficients lie in `H`.  The compatibility hypothesis is exactly what is
needed to form the restricted HNN extension over `H`.

This is the normal-form existence statement used for Borisov's irreducible
`{c,d}` and `{c,e}` contexts. -/
theorem exists_reducedWord_of_mem_generatedWithStable
    (H : Subgroup G)
    (hphi : ∀ a : A, (a : G) ∈ H ↔ (phi a : G) ∈ H)
    {x : HNNExtension G A B phi}
    (hx : x ∈ generatedWithStable (A := A) (B := B) (phi := phi) H) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G A B,
      w.prod phi = x ∧ w.head ∈ H ∧ ∀ p ∈ w.toList, p.2 ∈ H := by
  rw [← restrictedEmbedding_range H hphi] at hx
  rcases hx with ⟨y, rfl⟩
  let psi := restrictedPhi H hphi
  let : Nonempty (HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H)) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair H
      (restrictedA (A := A) H) (restrictedB (B := B) H) :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv psi d) y
  let wm := mapRestrictedReducedWord (A := A) (B := B) H w.toReducedWord
  refine ⟨wm, ?_, ?_, ?_⟩
  · rw [mapRestrictedReducedWord_prod H hphi]
    exact congrArg (restrictedEmbedding H hphi)
      ((HNNExtension.NormalWord.equiv psi d).symm_apply_apply y)
  · exact w.head.property
  · intro p hp
    dsimp [wm, mapRestrictedReducedWord] at hp
    rw [List.mem_map] at hp
    rcases hp with ⟨q, hq, rfl⟩
    exact q.2.property

/-- A centralizer HNN extension. -/
abbrev CentralizerHNN (G : Type*) [Group G] (C : Subgroup G) :=
  HNNExtension G C C (MulEquiv.refl C)

/-- The base-group inclusion into the HNN extension centralizing the chosen subgroup. -/
def centralizerOf (C : Subgroup G) : G →* CentralizerHNN G C :=
  HNNExtension.of

/-- The stable letter centralizing the chosen subgroup. -/
def centralizerStable (C : Subgroup G) : CentralizerHNN G C :=
  HNNExtension.t

/-- In a centralizer HNN extension, an element of the base group commutes
with the stable letter exactly when it belongs to the centralized subgroup.
This is the two-syllable form of Britton's lemma used at Borisov's final
`k`-stage. -/
theorem centralizerOf_commute_stable_iff (C : Subgroup G) (g : G) :
    Commute (centralizerOf C g) (centralizerStable C) ↔ g ∈ C := by
  constructor
  · intro hcomm
    let w₁ : HNNExtension.NormalWord.ReducedWord G C C :=
      { head := g
        toList := [(1, 1)]
        chain := List.isChain_singleton _ }
    let w₂ : HNNExtension.NormalWord.ReducedWord G C C :=
      { head := 1
        toList := [(1, g)]
        chain := List.isChain_singleton _ }
    have hprod : w₁.prod (MulEquiv.refl C) = w₂.prod (MulEquiv.refl C) := by
      simpa [w₁, w₂, HNNExtension.NormalWord.ReducedWord.prod,
        centralizerOf, centralizerStable] using hcomm.eq
    have hcoset :=
      (HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
        (MulEquiv.refl C) hprod).2 (1 : ℤˣ) (by simp [w₁])
    have hinv : g⁻¹ ∈ C := by simpa [w₁, w₂] using hcoset
    simpa using C.inv_mem hinv
  · intro hg
    let c : C := ⟨g, hg⟩
    have h := HNNExtension.t_mul_of (φ := MulEquiv.refl C) c
    change centralizerOf C g * centralizerStable C =
      centralizerStable C * centralizerOf C g
    simpa [centralizerOf, centralizerStable, c] using h.symm

/-- The stable letter conjugated by an element of the base group. -/
def conjugatedStable (C : Subgroup G) (P : G) : CentralizerHNN G C :=
  centralizerOf C P⁻¹ * centralizerStable C * centralizerOf C P

/-- The subgroup generated by `H` and one additional element `u`. -/
def generatedWith
    {E : Type*} [Group E] (H : Subgroup E) (u : E) : Subgroup E :=
  Subgroup.closure ((H : Set E) ∪ {u})

/-! Auxiliary restricted HNN extension for the calculation in
Lemma B.4 of the paper. -/

/-- The subgroup of `A` whose conjugates by `P` lie in `C`. -/
def conjugatePullback (A C : Subgroup G) (P : G) : Subgroup A :=
  C.comap ((MulAut.conj P).toMonoidHom.comp A.subtype)

/-- The homomorphism embedding the conjugated restricted centralizer HNN extension. -/
def conjugatedEmbedding (A C : Subgroup G) (P : G) :
    CentralizerHNN A (conjugatePullback A C P) →* CentralizerHNN G C :=
  HNNExtension.lift
    ((centralizerOf C).comp A.subtype) (conjugatedStable C P) (by
      intro a
      let c : C := ⟨P * ((a : conjugatePullback A C P) : A) * P⁻¹, a.property⟩
      have hc : (centralizerOf C (c : G)) * centralizerStable C =
          centralizerStable C * centralizerOf C (c : G) := by
        simpa [centralizerOf, centralizerStable] using
          HNNExtension.of_mul_t (φ := MulEquiv.refl C) c
      let aG : G := (((a : conjugatePullback A C P) : A) : G)
      change
        (centralizerOf C P⁻¹ * centralizerStable C * centralizerOf C P) *
            centralizerOf C aG =
          centralizerOf C aG *
            (centralizerOf C P⁻¹ * centralizerStable C * centralizerOf C P)
      have hPa : P * aG = (c : G) * P := by
        dsimp [aG, c]
        simp
      have hPinvc : P⁻¹ * (c : G) = aG * P⁻¹ := by
        dsimp [aG, c]
        simp [mul_assoc]
      calc
        _ = centralizerOf C P⁻¹ * centralizerStable C *
              (centralizerOf C P * centralizerOf C aG) := by simp [mul_assoc]
        _ = centralizerOf C P⁻¹ * centralizerStable C *
              centralizerOf C (P * aG) := by
                rw [map_mul (centralizerOf C) P aG]
        _ = centralizerOf C P⁻¹ * centralizerStable C *
              centralizerOf C ((c : G) * P) := by rw [hPa]
        _ = centralizerOf C P⁻¹ * centralizerStable C *
              (centralizerOf C (c : G) * centralizerOf C P) := by
                rw [map_mul (centralizerOf C) (c : G) P]
        _ = centralizerOf C P⁻¹ *
              (centralizerStable C * centralizerOf C (c : G)) *
                centralizerOf C P := by simp [mul_assoc]
        _ = centralizerOf C P⁻¹ *
              (centralizerOf C (c : G) * centralizerStable C) *
                centralizerOf C P := by rw [hc]
        _ = (centralizerOf C P⁻¹ * centralizerOf C (c : G)) *
              centralizerStable C * centralizerOf C P := by simp [mul_assoc]
        _ = centralizerOf C (P⁻¹ * (c : G)) *
              centralizerStable C * centralizerOf C P := by
                rw [map_mul (centralizerOf C) P⁻¹ (c : G)]
        _ = centralizerOf C (aG * P⁻¹) *
              centralizerStable C * centralizerOf C P := by rw [hPinvc]
        _ = (centralizerOf C aG * centralizerOf C P⁻¹) *
              centralizerStable C * centralizerOf C P := by
                rw [map_mul (centralizerOf C) aG P⁻¹]
        _ = centralizerOf C aG *
              (centralizerOf C P⁻¹ * centralizerStable C *
                centralizerOf C P) := by simp [mul_assoc])

@[simp]
private theorem conjugatedEmbedding_of (A C : Subgroup G) (P : G) (a : A) :
    conjugatedEmbedding A C P (HNNExtension.of a) = centralizerOf C (a : G) := by
  simp [conjugatedEmbedding]

@[simp]
private theorem conjugatedEmbedding_t (A C : Subgroup G) (P : G) :
    conjugatedEmbedding A C P HNNExtension.t = conjugatedStable C P := by
  simp [conjugatedEmbedding]

private theorem conjugatedEmbedding_range (A C : Subgroup G) (P : G) :
    MonoidHom.range (conjugatedEmbedding A C P) =
      generatedWith (A.map (centralizerOf C)) (conjugatedStable C P) := by
  apply le_antisymm
  · rintro x ⟨y, rfl⟩
    induction y using HNNExtension.induction_on with
    | of a =>
        apply Subgroup.subset_closure
        exact Or.inl ⟨a, a.property, by simp⟩
    | t =>
        apply Subgroup.subset_closure
        exact Or.inr (Set.mem_singleton _)
    | mul x y hx hy => simpa using Subgroup.mul_mem _ hx hy
    | inv x hx => simpa using Subgroup.inv_mem _ hx
  · unfold generatedWith
    rw [Subgroup.closure_le]
    rintro x (hx | rfl)
    · rcases hx with ⟨a, ha, rfl⟩
      exact ⟨HNNExtension.of (⟨a, ha⟩ : A), by simp⟩
    · exact ⟨HNNExtension.t, by simp⟩

private theorem centralizer_generatedWith_reducedWord
    (C D : Subgroup G) {x : CentralizerHNN G C}
    (hx : x ∈ generatedWith (D.map (centralizerOf C)) (centralizerStable C)) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G C C,
      w.prod (MulEquiv.refl C) = x ∧ w.head ∈ D ∧
        ∀ p ∈ w.toList, p.2 ∈ D := by
  have hphi : ∀ c : C,
      (c : G) ∈ D ↔ ((MulEquiv.refl C) c : G) ∈ D := by simp
  apply exists_reducedWord_of_mem_generatedWithStable D hphi
  simpa [generatedWith, generatedWithStable, centralizerOf, centralizerStable]
    using hx

/-- The syllable list obtained by conjugating a restricted reduced word. -/
def conjugatedList (P : G) : List (ℤˣ × A) → List (ℤˣ × G)
  | [] => []
  | [x] => [(x.1, P * (x.2 : G))]
  | x :: y :: xs =>
      (x.1, P * (x.2 : G) * P⁻¹) :: conjugatedList P (y :: xs)

private lemma conjugatedStable_zpow_unit (C : Subgroup G) (P : G) (u : ℤˣ) :
    conjugatedStable C P ^ (u : ℤ) =
      centralizerOf C P⁻¹ * centralizerStable C ^ (u : ℤ) *
        centralizerOf C P := by
  rcases Int.units_eq_one_or u with rfl | rfl <;>
    simp [conjugatedStable, mul_assoc]

private lemma conjugatedList_prod (A C : Subgroup G) (P : G)
    (l : List (ℤˣ × A)) (hl : l ≠ []) :
    ((conjugatedList P l).map
        (fun p => centralizerStable C ^ (p.1 : ℤ) * centralizerOf C p.2)).prod =
      centralizerOf C P * conjugatedEmbedding A C P
        ((l.map (fun p => HNNExtension.t ^ (p.1 : ℤ) * HNNExtension.of p.2)).prod) := by
  induction l with
  | nil => simp at hl
  | cons x xs ih =>
      cases xs with
      | nil =>
          simp [conjugatedList, conjugatedEmbedding, conjugatedStable_zpow_unit,
            map_mul, mul_assoc]
      | cons y ys =>
          have htail : y :: ys ≠ [] := by simp
          simp only [conjugatedList, List.map_cons, List.prod_cons]
          rw [ih htail]
          simp [conjugatedEmbedding, conjugatedStable_zpow_unit, map_mul, mul_assoc]

private lemma conjugated_toSubgroup_self {E : Type*} [Group E]
    (K : Subgroup E) (u : ℤˣ) :
    HNNExtension.toSubgroup K K u = K := by
  rcases Int.units_eq_one_or u with rfl | rfl <;> rfl

lemma conjugatedList_chain (A C : Subgroup G) (P : G)
    (l : List (ℤˣ × A))
    (hchain : l.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup (conjugatePullback A C P)
        (conjugatePullback A C P) a.1 → a.1 = b.1)) :
    (conjugatedList P l).IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup C C a.1 → a.1 = b.1) := by
  induction l with
  | nil => exact List.isChain_nil
  | cons x xs ih =>
      cases xs with
      | nil =>
          change [(x.1, P * (x.2 : G))].IsChain (fun a b =>
            a.2 ∈ HNNExtension.toSubgroup C C a.1 → a.1 = b.1)
          exact List.isChain_singleton _
      | cons y ys =>
          apply List.IsChain.cons
          · exact ih (List.isChain_cons.1 hchain).2
          · intro z hz hmem
            have hzfst : z.1 = y.1 := by
              cases ys <;>
                simp only [conjugatedList, List.head?_cons, Option.mem_def, Option.some.injEq] at hz
              · exact (congrArg Prod.fst hz).symm
              · exact (congrArg Prod.fst hz).symm
            have hxmem : x.2 ∈ conjugatePullback A C P := by
              change P * (x.2 : G) * P⁻¹ ∈ C
              rw [← conjugated_toSubgroup_self C x.1]
              exact hmem
            have hxmem' : x.2 ∈ HNNExtension.toSubgroup
                (conjugatePullback A C P) (conjugatePullback A C P) x.1 := by
              simpa [conjugated_toSubgroup_self] using hxmem
            have hxy := (List.isChain_cons.1 hchain).1 y (by simp) hxmem'
            exact hxy.trans hzfst.symm

/-- The reduced HNN word obtained from the conjugated restricted normal word. -/
def conjugatedReducedWord (A C : Subgroup G) (P : G)
    (w : HNNExtension.NormalWord.ReducedWord A
      (conjugatePullback A C P) (conjugatePullback A C P)) :
    HNNExtension.NormalWord.ReducedWord G C C where
  head := ((w.head : A) : G) * P⁻¹
  toList := conjugatedList P w.toList
  chain := conjugatedList_chain A C P w.toList w.chain

private lemma conjugatedReducedWord_prod (A C : Subgroup G) (P : G)
    (w : HNNExtension.NormalWord.ReducedWord A
      (conjugatePullback A C P) (conjugatePullback A C P))
    (hne : w.toList ≠ []) :
    (conjugatedReducedWord A C P w).prod (MulEquiv.refl C) =
      conjugatedEmbedding A C P (w.prod (MulEquiv.refl (conjugatePullback A C P))) := by
  change
    centralizerOf C (((w.head : A) : G) * P⁻¹) *
        ((conjugatedList P w.toList).map
          (fun p => centralizerStable C ^ (p.1 : ℤ) * centralizerOf C p.2)).prod =
      conjugatedEmbedding A C P
        (HNNExtension.of w.head *
          (w.toList.map
            (fun p => HNNExtension.t ^ (p.1 : ℤ) * HNNExtension.of p.2)).prod)
  rw [conjugatedList_prod A C P w.toList hne]
  simp [conjugatedEmbedding, centralizerOf, map_mul, mul_assoc]

private theorem conjugatedEmbedding_preimage_base
    (A C : Subgroup G) (P : G)
    (y : CentralizerHNN A (conjugatePullback A C P))
    (hy : conjugatedEmbedding A C P y ∈
      MonoidHom.range (centralizerOf C)) :
    ∃ a : A, y = HNNExtension.of a := by
  let K := conjugatePullback A C P
  let : Nonempty (HNNExtension.NormalWord.TransversalPair A K K) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair A K K :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d) y
  have hwy : w.toReducedWord.prod (MulEquiv.refl K) = y :=
    (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d).symm_apply_apply y
  by_cases hnil : w.toList = []
  · refine ⟨w.head, ?_⟩
    rw [← hwy]
    simp [HNNExtension.NormalWord.ReducedWord.prod, hnil]
  · let wm := conjugatedReducedWord A C P w.toReducedWord
    have hwm : wm.prod (MulEquiv.refl C) = conjugatedEmbedding A C P y := by
      dsimp [wm]
      rw [conjugatedReducedWord_prod A C P w.toReducedWord hnil, hwy]
    have hwbase : wm.prod (MulEquiv.refl C) ∈
        MonoidHom.range (centralizerOf C) := by
      rwa [hwm]
    have hwempty :=
      HNNExtension.ReducedWord.toList_eq_nil_of_mem_of_range
        (MulEquiv.refl C) wm hwbase
    have : w.toList = [] := by
      cases hlist : w.toList with
      | nil => rfl
      | cons q qs =>
          exfalso
          rcases q with ⟨u, a⟩
          dsimp [wm, conjugatedReducedWord] at hwempty
          rw [hlist] at hwempty
          cases qs <;> simp [conjugatedList] at hwempty
    exact (hnil this).elim

/-- The subgroup generated by an embedded subgroup `A` and the conjugate
`P⁻¹tP` meets the ambient base group exactly in `A`. -/
theorem generatedWith_conjugatedStable_inf_base
    (A C : Subgroup G) (P : G) :
    generatedWith (A.map (centralizerOf C)) (conjugatedStable C P) ⊓
        MonoidHom.range (centralizerOf C) =
      A.map (centralizerOf C) := by
  ext x
  constructor
  · intro hx
    have hxleft := hx.1
    rw [← conjugatedEmbedding_range A C P] at hxleft
    rcases hxleft with ⟨y, hy⟩
    have hybase : conjugatedEmbedding A C P y ∈
        MonoidHom.range (centralizerOf C) := by
      simpa [hy] using hx.2
    rcases conjugatedEmbedding_preimage_base A C P y hybase with ⟨a, rfl⟩
    rw [conjugatedEmbedding_of] at hy
    exact ⟨a, a.property, hy⟩
  · rintro ⟨a, ha, rfl⟩
    constructor
    · apply Subgroup.subset_closure
      exact Or.inl ⟨a, ha, rfl⟩
    · exact ⟨a, rfl⟩

/-- A conjugate of the stable letter cannot lie in the embedded base group.
This is the one-stable-letter case of Britton's lemma. -/
theorem conjugatedStable_not_mem_base (C : Subgroup G) (q : G) :
    conjugatedStable C q ∉ MonoidHom.range (centralizerOf C) := by
  intro hbase
  let w : HNNExtension.NormalWord.ReducedWord G C C :=
    { head := q⁻¹
      toList := [(1, q)]
      chain := List.isChain_singleton _ }
  have hwprod : w.prod (MulEquiv.refl C) = conjugatedStable C q := by
    simp [w, HNNExtension.NormalWord.ReducedWord.prod, conjugatedStable,
      centralizerOf, centralizerStable, mul_assoc]
  have hwbase : w.prod (MulEquiv.refl C) ∈
      MonoidHom.range (centralizerOf C) := by
    rwa [hwprod]
  have hnil :=
    HNNExtension.ReducedWord.toList_eq_nil_of_mem_of_range
      (MulEquiv.refl C) w hwbase
  simp [w] at hnil

/-- Exact first-coefficient consequence of membership in the subgroup
generated by `A` and `P⁻¹tP`. -/
theorem conjugatedStable_mem_generatedWith_imp_doubleCoset
    (A C : Subgroup G) (P Q : G)
    (hQ : conjugatedStable C Q ∈
      generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)) :
    ∃ c : C, ∃ a : A, P = (c : G) * Q * (a : G) := by
  rw [← conjugatedEmbedding_range A C P] at hQ
  rcases hQ with ⟨y, hy⟩
  let K := conjugatePullback A C P
  let : Nonempty (HNNExtension.NormalWord.TransversalPair A K K) :=
    HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
  let d : HNNExtension.NormalWord.TransversalPair A K K :=
    Classical.choice inferInstance
  let w : HNNExtension.NormalWord d :=
    (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d) y
  have hwy : w.toReducedWord.prod (MulEquiv.refl K) = y :=
    (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d).symm_apply_apply y
  have hne : w.toList ≠ [] := by
    intro hnil
    have hybase : conjugatedEmbedding A C P y ∈
        MonoidHom.range (centralizerOf C) := by
      refine ⟨(w.head : A), ?_⟩
      rw [← hwy]
      simp only [HNNExtension.NormalWord.ReducedWord.prod, hnil,
        List.map_nil, List.prod_nil, mul_one]
      exact (conjugatedEmbedding_of A C P w.head).symm
    exact conjugatedStable_not_mem_base C Q (hy ▸ hybase)
  let wm := conjugatedReducedWord A C P w.toReducedWord
  let qword : HNNExtension.NormalWord.ReducedWord G C C :=
    { head := Q⁻¹
      toList := [(1, Q)]
      chain := List.isChain_singleton _ }
  have hwm : wm.prod (MulEquiv.refl C) =
      conjugatedEmbedding A C P y := by
    dsimp [wm]
    rw [conjugatedReducedWord_prod A C P w.toReducedWord hne, hwy]
  have hqword : qword.prod (MulEquiv.refl C) = conjugatedStable C Q := by
    simp [qword, HNNExtension.NormalWord.ReducedWord.prod,
      conjugatedStable, centralizerOf, centralizerStable, mul_assoc]
  have hprod : wm.prod (MulEquiv.refl C) =
      qword.prod (MulEquiv.refl C) := hwm.trans (hy.trans hqword.symm)
  have hcompare := HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
    (MulEquiv.refl C) hprod
  cases hlist : w.toList with
  | nil => exact (hne hlist).elim
  | cons p xs =>
      rcases p with ⟨u, aTail⟩
      have hu : u ∈ Option.map Prod.fst wm.toList.head? := by
        dsimp [wm, conjugatedReducedWord]
        rw [hlist]
        cases xs <;> simp [conjugatedList]
      have hdelta' := hcompare.2 u hu
      have hdelta : (((w.head : A) : G) * P⁻¹)⁻¹ * Q⁻¹ ∈ C := by
        simpa [qword, wm, conjugatedReducedWord, conjugated_toSubgroup_self]
          using hdelta'
      let c : C := ⟨(((w.head : A) : G) * P⁻¹)⁻¹ * Q⁻¹, hdelta⟩
      refine ⟨c, w.head, ?_⟩
      dsimp [c]
      simp [mul_assoc]

/-- The product set `Delta * B₀ * Delta` appearing in Lemma B.5 of the paper. -/
def deltaDoubleCoset (Delta B₀ : Subgroup G) : Set G :=
  {x | ∃ d₁ ∈ Delta, ∃ b ∈ B₀, ∃ d₂ ∈ Delta, x = d₁ * b * d₂}

private lemma centralizer_of_mul_tpow (Delta : Subgroup G) (u : ℤˣ) (d : Delta) :
    (HNNExtension.of (d : G) : CentralizerHNN G Delta) *
        HNNExtension.t ^ (u : ℤ) =
      HNNExtension.t ^ (u : ℤ) * HNNExtension.of (d : G) := by
  rcases Int.units_eq_one_or u with rfl | rfl
  · simpa using HNNExtension.of_mul_t (φ := MulEquiv.refl Delta) d
  · simpa using HNNExtension.of_mul_inv_t (φ := MulEquiv.refl Delta) d

/-- The reduced word with the specified initial coefficient and syllable chain. -/
def centralizerReducedWord (Delta : Subgroup G) (g : G)
    (l : List (ℤˣ × G))
    (chain : l.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1)) :
    HNNExtension.NormalWord.ReducedWord G Delta Delta :=
  ⟨g, l, chain⟩

private lemma centralizer_tail_prod_eq (Delta : Subgroup G)
    (g₁ g₂ a b : G) (u : ℤˣ) (l₁ l₂ : List (ℤˣ × G))
    (c₁ : ((u, a) :: l₁).IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (c₂ : ((u, b) :: l₂).IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (hd : g₁⁻¹ * g₂ ∈ Delta)
    (heq :
      (centralizerReducedWord Delta g₁ ((u, a) :: l₁) c₁).prod
          (MulEquiv.refl Delta) =
        (centralizerReducedWord Delta g₂ ((u, b) :: l₂) c₂).prod
          (MulEquiv.refl Delta)) :
    (centralizerReducedWord Delta a l₁ (List.isChain_cons.1 c₁).2).prod
        (MulEquiv.refl Delta) =
      (centralizerReducedWord Delta ((g₁⁻¹ * g₂) * b) l₂
        (List.isChain_cons.1 c₂).2).prod (MulEquiv.refl Delta) := by
  let d : Delta := ⟨g₁⁻¹ * g₂, hd⟩
  have hc := centralizer_of_mul_tpow Delta u d
  dsimp [centralizerReducedWord, HNNExtension.NormalWord.ReducedWord.prod] at heq ⊢
  have heq' := congrArg
    (fun x : CentralizerHNN G Delta =>
      (HNNExtension.of g₁ * HNNExtension.t ^ (u : ℤ))⁻¹ * x) heq
  simp only [mul_inv_rev] at heq'
  simp only [List.map_cons, List.prod_cons, mul_assoc, inv_mul_cancel_left] at heq'
  rw [← mul_assoc (HNNExtension.of g₁)⁻¹ (HNNExtension.of g₂) _] at heq'
  rw [← map_inv, ← map_mul] at heq'
  rw [← mul_assoc (HNNExtension.of (g₁⁻¹ * g₂))
    (HNNExtension.t ^ (u : ℤ)) _] at heq'
  rw [hc] at heq'
  change _ = HNNExtension.of ((d : G) * b) * _
  simpa [mul_assoc] using heq'

private lemma centralizer_toSubgroup_self (Delta : Subgroup G) (u : ℤˣ) :
    HNNExtension.toSubgroup Delta Delta u = Delta := by
  rcases Int.units_eq_one_or u with rfl | rfl <;> rfl

/-!
For two equal reduced words in a centralizer HNN extension, comparison of
their first base coefficients gives an element of `Delta`.  Commuting that
element through the first stable letter lets us repeat the argument on the
tails.  This is the coefficient-by-coefficient form of the normal-form
argument needed in Lemma B.5 of the paper.
-/
private lemma centralizer_reduced_coefficients
    (Delta L B₀ C : Subgroup G)
    (hinter : (L : Set G) ∩ deltaDoubleCoset Delta B₀ = (C : Set G))
    (g₁ g₂ : G) (l₁ l₂ : List (ℤˣ × G))
    (c₁ : l₁.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (c₂ : l₂.IsChain (fun a b =>
      a.2 ∈ HNNExtension.toSubgroup Delta Delta a.1 → a.1 = b.1))
    (hprod : (centralizerReducedWord Delta g₁ l₁ c₁).prod
        (MulEquiv.refl Delta) =
      (centralizerReducedWord Delta g₂ l₂ c₂).prod
        (MulEquiv.refl Delta))
    (hg₁ : g₁ ∈ L) (hl₁ : ∀ x ∈ l₁, x.2 ∈ L)
    (hg₂ : g₂ ∈ deltaDoubleCoset Delta B₀)
    (hl₂ : ∀ x ∈ l₂, x.2 ∈ B₀) :
    g₁ ∈ C ∧ ∀ x ∈ l₁, x.2 ∈ C := by
  induction l₁ generalizing g₁ g₂ l₂ with
  | nil =>
      have hmaps :=
        (HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
          (MulEquiv.refl Delta) hprod).1
      cases l₂ with
      | cons q qs => simp [centralizerReducedWord] at hmaps
      | nil =>
          have heqOf : HNNExtension.of g₁ =
              (HNNExtension.of g₂ : CentralizerHNN G Delta) := by
            simpa [centralizerReducedWord,
              HNNExtension.NormalWord.ReducedWord.prod] using hprod
          have hg : g₁ = g₂ := HNNExtension.of_injective
            (A := Delta) (B := Delta) (φ := MulEquiv.refl Delta) heqOf
          have hdc : g₁ ∈ deltaDoubleCoset Delta B₀ := by
            simpa [hg] using hg₂
          have hgC : g₁ ∈ C :=
            (Set.ext_iff.mp hinter g₁).mp ⟨hg₁, hdc⟩
          exact ⟨hgC, by simp⟩
  | cons p ps ih =>
      have hcompare := HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
        (MulEquiv.refl Delta) hprod
      cases l₂ with
      | nil => simp [centralizerReducedWord] at hcompare
      | cons q qs =>
          rcases p with ⟨u, a⟩
          rcases q with ⟨v, b⟩
          have hmaps := hcompare.1
          change u :: ps.map Prod.fst = v :: qs.map Prod.fst at hmaps
          have huv : u = v := (List.cons.inj hmaps).1
          subst v
          have hd : g₁⁻¹ * g₂ ∈ Delta := by
            have hd' := hcompare.2 u (by simp [centralizerReducedWord])
            change g₁⁻¹ * g₂ ∈
              HNNExtension.toSubgroup Delta Delta (-u) at hd'
            simpa [centralizer_toSubgroup_self] using hd'
          let d : Delta := ⟨g₁⁻¹ * g₂, hd⟩
          have hdc : g₁ ∈ deltaDoubleCoset Delta B₀ := by
            rcases hg₂ with ⟨d₁, hd₁, b₀, hb₀, d₂, hd₂, rfl⟩
            refine ⟨d₁, hd₁, b₀, hb₀, d₂ * d⁻¹,
              Delta.mul_mem hd₂ (Delta.inv_mem hd), ?_⟩
            dsimp [d]
            simp [mul_assoc]
          have hgC : g₁ ∈ C :=
            (Set.ext_iff.mp hinter g₁).mp ⟨hg₁, hdc⟩
          have hc₁tail := (List.isChain_cons.1 c₁).2
          have hc₂tail := (List.isChain_cons.1 c₂).2
          have htailprod := centralizer_tail_prod_eq Delta
            g₁ g₂ a b u ps qs c₁ c₂ hd hprod
          have haL : a ∈ L := hl₁ (u, a) (by simp)
          have hbB : b ∈ B₀ := hl₂ (u, b) (by simp)
          have htailHead : (d : G) * b ∈ deltaDoubleCoset Delta B₀ :=
            ⟨d, hd, b, hbB, 1, Delta.one_mem, by simp⟩
          have htail := ih a ((d : G) * b) qs hc₁tail hc₂tail htailprod haL
            (by
              intro x hx
              exact hl₁ x (List.mem_cons_of_mem _ hx))
            htailHead
            (by
              intro x hx
              exact hl₂ x (List.mem_cons_of_mem _ hx))
          refine ⟨hgC, ?_⟩
          intro x hx
          rcases List.mem_cons.1 hx with rfl | hx
          · exact htail.1
          · exact htail.2 x hx

private lemma exists_reducedWord_for_generatedWith
    (Delta H : Subgroup G)
    {x : CentralizerHNN G Delta}
    (hx : x ∈ generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta)) :
    ∃ w : HNNExtension.NormalWord.ReducedWord G Delta Delta,
      w.prod (MulEquiv.refl Delta) = x ∧ w.head ∈ H ∧
        ∀ p ∈ w.toList, p.2 ∈ H :=
  centralizer_generatedWith_reducedWord Delta H hx

private lemma reducedWord_prod_mem_generatedWith
    (Delta H : Subgroup G)
    (w : HNNExtension.NormalWord.ReducedWord G Delta Delta)
    (hhead : w.head ∈ H) (hlist : ∀ p ∈ w.toList, p.2 ∈ H) :
    w.prod (MulEquiv.refl Delta) ∈
      generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta) := by
  let K := generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta)
  have hof : HNNExtension.of w.head ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inl ⟨w.head, hhead, rfl⟩
  have ht : (HNNExtension.t : CentralizerHNN G Delta) ∈ K := by
    apply Subgroup.subset_closure
    exact Or.inr rfl
  have hprodListAux : ∀ l : List (ℤˣ × G),
      (∀ p ∈ l, p.2 ∈ H) →
      (l.map (fun p => HNNExtension.t ^ (p.1 : ℤ) * HNNExtension.of p.2)).prod ∈ K := by
    intro l hl
    induction l with
    | nil => simp [K]
    | cons p ps ih =>
        rw [List.map_cons, List.prod_cons]
        apply K.mul_mem
        · apply K.mul_mem
          · exact K.zpow_mem ht _
          · apply Subgroup.subset_closure
            exact Or.inl ⟨p.2, hl p (by simp), rfl⟩
        · exact ih (by
            intro q hq
            exact hl q (List.mem_cons_of_mem _ hq))
  exact K.mul_mem hof (hprodListAux w.toList hlist)

private lemma generatedWith_mono (Delta : Subgroup G) {H K : Subgroup G}
    (hHK : H ≤ K) :
    generatedWith (H.map (centralizerOf Delta)) (centralizerStable Delta) ≤
      generatedWith (K.map (centralizerOf Delta)) (centralizerStable Delta) := by
  unfold generatedWith
  apply Subgroup.closure_mono
  exact Set.union_subset_union (Subgroup.map_mono hHK) Set.Subset.rfl

/-- Lemma B.5 of the paper: intersection inside a centralizer HNN extension. -/
theorem centralizer_intersection
    (Delta L B₀ C : Subgroup G)
    (hCL : C ≤ L) (hCB₀ : C ≤ B₀)
    (hinter : (L : Set G) ∩ deltaDoubleCoset Delta B₀ = (C : Set G)) :
    generatedWith (L.map (centralizerOf Delta)) (centralizerStable Delta) ⊓
        generatedWith (B₀.map (centralizerOf Delta)) (centralizerStable Delta) =
      generatedWith (C.map (centralizerOf Delta)) (centralizerStable Delta) := by
  ext x
  constructor
  · intro hx
    rcases exists_reducedWord_for_generatedWith Delta L hx.1 with
      ⟨wL, hwL, hwLhead, hwLlist⟩
    rcases exists_reducedWord_for_generatedWith Delta B₀ hx.2 with
      ⟨wB, hwB, hwBhead, hwBlist⟩
    have hwBhead' : wB.head ∈ deltaDoubleCoset Delta B₀ :=
      ⟨1, Delta.one_mem, wB.head, hwBhead, 1, Delta.one_mem, by simp⟩
    have hcoeff := centralizer_reduced_coefficients Delta L B₀ C
      hinter
      wL.head wB.head wL.toList wB.toList wL.chain wB.chain
      (hwL.trans hwB.symm) hwLhead hwLlist hwBhead' hwBlist
    have hm := reducedWord_prod_mem_generatedWith Delta C wL hcoeff.1 hcoeff.2
    rwa [hwL] at hm
  · intro hx
    exact ⟨generatedWith_mono Delta hCL hx, generatedWith_mono Delta hCB₀ hx⟩

/-- The nested normal-form calculation used in the proof of
Proposition 3.8 of the paper.

Inside the centralizer HNN extension of `G` over `C`, let `p = P⁻¹tP`.
If `A ≤ B₀`, `C ≤ B₀`, `C₀ ≤ C`, and `P ∉ B₀`, then the
subgroup generated by `C₀` and `t` meets

`<A,p> · B₀ · <A,p>`

exactly in the embedded copy of `C₀`.  The proof first takes a reduced
`p`-word with coefficients in `B₀`, substitutes `p = P⁻¹tP`, and compares
it with a reduced `t`-word whose coefficients lie in `C₀`.  A first stable
letter would force `P ∈ B₀`; hence the `p`-length is zero, after which the
restricted-HNN intersection lemma applies. -/
theorem conjugated_doubleCoset_intersection
    (A C B₀ C₀ : Subgroup G)
    (hAB : A ≤ B₀) (hCB : C ≤ B₀) (hC₀C : C₀ ≤ C)
    (P : G) (hP : P ∉ B₀) :
    ((generatedWith (C₀.map (centralizerOf C)) (centralizerStable C) :
        Subgroup (CentralizerHNN G C)) : Set (CentralizerHNN G C)) ∩
        deltaDoubleCoset
          (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P))
          (B₀.map (centralizerOf C)) =
      (C₀.map (centralizerOf C) : Set (CentralizerHNN G C)) := by
  let L : Subgroup (CentralizerHNN G C) :=
    generatedWith (C₀.map (centralizerOf C)) (centralizerStable C)
  let Delta : Subgroup (CentralizerHNN G C) :=
    generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)
  let B₀' : Subgroup (CentralizerHNN G C) := B₀.map (centralizerOf C)
  let Wide : Subgroup (CentralizerHNN G C) :=
    generatedWith (B₀.map (centralizerOf C)) (conjugatedStable C P)
  have hDeltaWide : Delta ≤ Wide := by
    unfold Delta Wide generatedWith
    apply Subgroup.closure_mono
    exact Set.union_subset_union (Subgroup.map_mono hAB) Set.Subset.rfl
  ext x
  constructor
  · rintro ⟨hxL, hxdc⟩
    have hxWide : x ∈ Wide := by
      rcases hxdc with ⟨d₁, hd₁, b, hb, d₂, hd₂, rfl⟩
      exact Wide.mul_mem
        (Wide.mul_mem (hDeltaWide hd₁) (by
          apply Subgroup.subset_closure
          exact Or.inl hb))
        (hDeltaWide hd₂)
    have hxRange : x ∈ MonoidHom.range (conjugatedEmbedding B₀ C P) := by
      rw [conjugatedEmbedding_range B₀ C P]
      exact hxWide
    rcases hxRange with ⟨y, hyx⟩
    let K := conjugatePullback B₀ C P
    let : Nonempty (HNNExtension.NormalWord.TransversalPair B₀ K K) :=
      HNNExtension.NormalWord.TransversalPair.nonempty _ _ _
    let d : HNNExtension.NormalWord.TransversalPair B₀ K K :=
      Classical.choice inferInstance
    let w : HNNExtension.NormalWord d :=
      (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d) y
    have hwy : w.toReducedWord.prod (MulEquiv.refl K) = y :=
      (HNNExtension.NormalWord.equiv (MulEquiv.refl K) d).symm_apply_apply y
    by_cases hnil : w.toList = []
    · have hybase : y = HNNExtension.of w.head := by
        rw [← hwy]
        simp [HNNExtension.NormalWord.ReducedWord.prod, hnil]
      have hxbase : x ∈ MonoidHom.range (centralizerOf C) := by
        refine ⟨(w.head : B₀), ?_⟩
        rw [← hyx, hybase]
        simp [conjugatedEmbedding_of]
      have hcompat : ∀ c : C,
          (c : G) ∈ C₀ ↔ ((MulEquiv.refl C) c : G) ∈ C₀ := by simp
      have hinter := generatedWithStable_inf_base
        (A := C) (B := C) (phi := MulEquiv.refl C) C₀ hcompat
      have hxC₀' : x ∈ C₀.map
          (HNNExtension.of (A := C) (B := C) (φ := MulEquiv.refl C)) := by
        rw [← hinter]
        constructor
        · simpa [L, generatedWith, generatedWithStable,
            centralizerOf, centralizerStable] using hxL
        · exact hxbase
      simpa [centralizerOf] using hxC₀'
    · rcases exists_reducedWord_for_generatedWith C C₀ hxL with
        ⟨wL, hwL, hwLhead, hwLlist⟩
      let wm := conjugatedReducedWord B₀ C P w.toReducedWord
      have hwm : wm.prod (MulEquiv.refl C) = conjugatedEmbedding B₀ C P y := by
        dsimp [wm]
        rw [conjugatedReducedWord_prod B₀ C P w.toReducedWord hnil, hwy]
      have hprod : wm.prod (MulEquiv.refl C) = wL.prod (MulEquiv.refl C) := by
        rw [hwm, hyx, hwL]
      have hcompare := HNNExtension.ReducedWord.map_fst_eq_and_of_prod_eq
        (MulEquiv.refl C) hprod
      cases hlist : w.toList with
      | nil => exact (hnil hlist).elim
      | cons q qs =>
          rcases q with ⟨u, b⟩
          have hu : u ∈ Option.map Prod.fst wm.toList.head? := by
            dsimp [wm, conjugatedReducedWord]
            rw [hlist]
            cases qs <;> simp [conjugatedList]
          have hd' := hcompare.2 u hu
          have hd : (((w.head : B₀) : G) * P⁻¹)⁻¹ * wL.head ∈ C := by
            change wm.head⁻¹ * wL.head ∈ C
            simpa [centralizer_toSubgroup_self] using hd'
          have hPin : P ∈ B₀ := by
            have hm := B₀.mul_mem
              (B₀.mul_mem (hCB hd) (B₀.inv_mem (hCB (hC₀C hwLhead))))
              w.head.property
            simpa [mul_assoc] using hm
          exact (hP hPin).elim
  · intro hxC₀
    constructor
    · apply Subgroup.subset_closure
      exact Or.inl hxC₀
    · refine ⟨1, Delta.one_mem, x, ?_, 1, Delta.one_mem, by simp⟩
      exact Subgroup.map_mono (hC₀C.trans hCB) hxC₀

end HNNLemmas
end Undecidability
