/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import LeanPool.SmallUndecidableGroups.Borisov.Model.CStage
public import Mathlib.Data.Fin.VecNotation
public import LeanPool.SmallUndecidableGroups.Borisov.Assertions.AssertionIVBoundary
public import LeanPool.SmallUndecidableGroups.Borisov.Model.G0NormalForm
public import LeanPool.SmallUndecidableGroups.GroupTheory.MultipleHNN.Flat

/-!
# The base subgroup in Borisov's two-HNN model

This file identifies the subgroup generated by `d₃,e₃` with the image of the
original rank-two free base in `Γ₃`.  It is the bridge needed to apply the
two-stable-letter Britton lemma to the intersection input of Borisov's
Lemma 4.
-/

@[expose] public section

namespace Undecidability
namespace BorisovBaseRange

open BorisovCStage
open BorisovHNNModel

noncomputable section

theorem baseEmbedding_eq_lift :
    of1.comp of0 = FreeGroup.lift ![d3, e3] := by
  apply FreeGroup.ext_hom
  intro i
  fin_cases i <;> rfl

/-- The displayed subgroup `<d₃,e₃>` is exactly the embedded original
free-group base. -/
theorem DE3_eq_range_baseEmbedding :
    DE3 = MonoidHom.range (of1.comp of0) := by
  have hset : Set.range ![d3, e3] = ({d3, e3} : Set Gamma3) := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩
      fin_cases i <;> simp
    · intro hx
      rcases hx with rfl | hx
      · exact ⟨0, rfl⟩
      · have hx' : x = e3 := by simpa using hx
        exact ⟨1, hx'.symm⟩
  rw [DE3, baseEmbedding_eq_lift, FreeGroup.range_lift_eq_closure, hset]

end

end BorisovBaseRange
end Undecidability

/-!
# Borisov's Assertion IV

This file turns the four boundary computations into the full rank-five
freeness statement.  A signed displayed generator is expanded literally as
a flat word in the two HNN stable letters; the coefficient at a boundary is
exactly the coefficient studied in `AssertionIVBoundary.lean`.
-/

namespace Undecidability
namespace BorisovAssertionIV

open BorisovHNNModel
open BorisovIntersections
open BorisovG0HNN
open BorisovG0NormalForm
open BorisovAssertionIVBoundary

noncomputable section

/-- A stable-letter syllable in the flattened two-HNN-extension model. -/
abbrev FlatSyllable :=
  MultipleHNNFlat.Syllable (G := BorisovHNNModel.Base)
/-- A reduced word in the flattened two-HNN-extension model. -/
abbrev FlatWord := MultipleHNNFlat.ReducedWord A0 B0

/-- Convert a Boolean orientation to the signed unit `1` or `-1`. -/
def signedUnit : Bool → ℤˣ
  | true => 1
  | false => -1

@[simp] theorem signedUnit_true : signedUnit true = 1 := rfl

/-- The sequence of stable-letter colors in the expansion of a signed basis letter. -/
def factorColors (rules : Fin 3 → List (Fin 2)) : Basis × Bool → List (Fin 2)
  | (.inl beta, _) => [beta]
  | (.inr i, true) => rules i
  | (.inr i, false) => (rules i).reverse

theorem factorColors_ne_nil
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) : factorColors rules x ≠ [] := by
  rcases x with ⟨q, sign⟩
  cases q with
  | inl beta => simp [factorColors]
  | inr i =>
      cases sign <;> simp [factorColors, hne i]

/-- The syllables in a run of same-sign stable letters, with the supplied final coefficient. -/
def run (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) : List FlatSyllable :=
  colors.dropLast.map (fun color ↦
      { color := color, sign := u, coeff := 1 }) ++
    [{ color := colors.getLast hne, sign := u, coeff := lastCoeff }]

@[simp] theorem run_ne_nil (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    run colors hne u lastCoeff ≠ [] := by
  simp [run]

private theorem isChain_of_constant_sign
    (u : ℤˣ) (l : List FlatSyllable)
    (hsign : ∀ s ∈ l, s.sign = u) :
    l.IsChain (MultipleHNNFlat.Rel A0 B0) := by
  induction l with
  | nil => simp
  | cons x xs ih =>
      cases xs with
      | nil => simp
      | cons y ys =>
          rw [List.isChain_cons_cons]
          constructor
          · intro _ _
            rw [hsign x (by simp), hsign y (by simp)]
          · apply ih
            intro z hz
            exact hsign z (by simp [hz])

theorem run_chain (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    (run colors hne u lastCoeff).IsChain (MultipleHNNFlat.Rel A0 B0) := by
  apply isChain_of_constant_sign u
  intro s hs
  simp only [run, List.mem_append, List.mem_map, List.mem_singleton] at hs
  rcases hs with ⟨color, hcolor, rfl⟩ | rfl <;> rfl

@[simp] theorem run_getLast (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    (run colors hne u lastCoeff).getLast (run_ne_nil colors hne u lastCoeff) =
      { color := colors.getLast hne, sign := u, coeff := lastCoeff } := by
  simp [run]

@[simp] theorem run_head_color (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    ((run colors hne u lastCoeff).head
      (run_ne_nil colors hne u lastCoeff)).color = colors.head hne := by
  cases colors with
  | nil => exact (hne rfl).elim
  | cons c cs =>
      cases cs with
      | nil => simp [run]
      | cons d ds => simp [run]

@[simp] theorem run_head_sign (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    ((run colors hne u lastCoeff).head
      (run_ne_nil colors hne u lastCoeff)).sign = u := by
  cases colors with
  | nil => exact (hne rfl).elim
  | cons c cs =>
      cases cs with
      | nil => simp [run]
      | cons d ds => simp [run]

/-- The stable-letter run expanding one signed basis letter. -/
def factorRun (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    List FlatSyllable :=
  run (factorColors rules x) (factorColors_ne_nil rules hne x)
    (signedUnit x.2) lastCoeff

@[simp] theorem factorRun_ne_nil
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    factorRun rules hne x lastCoeff ≠ [] :=
  run_ne_nil _ _ _ _

theorem factorRun_chain
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    (factorRun rules hne x lastCoeff).IsChain
      (MultipleHNNFlat.Rel A0 B0) :=
  run_chain _ _ _ _

theorem factorColors_head
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) :
    (factorColors rules x).head (factorColors_ne_nil rules hne x) =
      firstStable rules hne x := by
  rcases x with ⟨q, sign⟩
  cases q with
  | inl beta => cases sign <;> simp [factorColors, firstStable]
  | inr i =>
      cases sign
      · simp [factorColors, firstStable, ruleLast]
      · simp [factorColors, firstStable, ruleFirst]

theorem factorColors_getLast
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) :
    (factorColors rules x).getLast (factorColors_ne_nil rules hne x) =
      lastStable rules hne x := by
  rcases x with ⟨q, sign⟩
  cases q with
  | inl beta => cases sign <;> simp [factorColors, lastStable]
  | inr i =>
      cases sign
      · simp [factorColors, lastStable, ruleFirst]
      · simp [factorColors, lastStable, ruleLast]

theorem factorRun_head_color
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).head
      (factorRun_ne_nil rules hne x lastCoeff)).color =
        firstStable rules hne x := by
  simp [factorRun, factorColors_head rules hne x]

theorem factorRun_head_sign
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).head
      (factorRun_ne_nil rules hne x lastCoeff)).sign = signedUnit x.2 := by
  simp [factorRun]

theorem factorRun_getLast_color
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).getLast
      (factorRun_ne_nil rules hne x lastCoeff)).color =
        lastStable rules hne x := by
  simp [factorRun, factorColors_getLast rules hne x]

theorem factorRun_getLast_sign
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).getLast
      (factorRun_ne_nil rules hne x lastCoeff)).sign = signedUnit x.2 := by
  simp [factorRun]

theorem factorRun_getLast_coeff
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).getLast
      (factorRun_ne_nil rules hne x lastCoeff)).coeff = lastCoeff := by
  simp [factorRun]

/-- The initial coefficient contributed by the next signed basis letter, or the identity. -/
def nextPrefix : List (Basis × Bool) → BorisovHNNModel.Base
  | [] => 1
  | y :: _ => factorPrefix y

/-- The flattened tail obtained by expanding a list of signed basis letters. -/
def expansionTail (rules : Fin 3 → List (Fin 2))
    (hne : ∀ i, rules i ≠ []) : List (Basis × Bool) → List FlatSyllable
  | [] => []
  | x :: xs =>
      factorRun rules hne x (suffix x * nextPrefix xs) ++
        expansionTail rules hne xs

/-- The initial coefficient of an expanded list of signed basis letters. -/
def expansionHead : List (Basis × Bool) → BorisovHNNModel.Base
  | [] => 1
  | x :: _ => factorPrefix x

private theorem factor_boundary_rel
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x y : Basis × Bool)
    (hreduced : x.1 = y.1 → x.2 = y.2)
    (nextLastCoeff : BorisovHNNModel.Base) :
    MultipleHNNFlat.Rel A0 B0
      ((factorRun rules hne x (boundaryCoefficient x y)).getLast
        (factorRun_ne_nil rules hne x (boundaryCoefficient x y)))
      ((factorRun rules hne y nextLastCoeff).head
        (factorRun_ne_nil rules hne y nextLastCoeff)) := by
  intro hcolor hmem
  rw [factorRun_getLast_sign, factorRun_head_sign]
  by_cases hsign : x.2 = y.2
  · rw [hsign]
  · exfalso
    have hstable : lastStable rules hne x = firstStable rules hne y := by
      rw [← factorRun_getLast_color rules hne x (boundaryCoefficient x y),
        ← factorRun_head_color rules hne y nextLastCoeff]
      exact hcolor
    have hnot := no_boundary_pinch_of_reduced_pair
      rules hne x y hreduced hsign hstable
    apply hnot
    have hmem' : boundaryCoefficient x y ∈
        HNNExtension.toSubgroup A0 B0 (signedUnit x.2) := by
      simpa only [factorRun_getLast_coeff, factorRun_getLast_sign] using hmem
    cases hx : x.2 <;>
      simpa [associatedForSign, signedUnit, hx] using hmem'

theorem expansionTail_chain
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (letters : List (Basis × Bool))
    (hreduced : letters.IsChain (fun x y ↦ x.1 = y.1 → x.2 = y.2)) :
    (expansionTail rules hne letters).IsChain
      (MultipleHNNFlat.Rel A0 B0) := by
  induction letters with
  | nil => simp [expansionTail]
  | cons x xs ih =>
      have hxs : xs.IsChain (fun x y ↦ x.1 = y.1 → x.2 = y.2) :=
        (List.isChain_cons.1 hreduced).2
      apply List.IsChain.append
        (factorRun_chain rules hne x (suffix x * nextPrefix xs))
        (ih hxs)
      cases xs with
      | nil => simp [expansionTail]
      | cons y ys =>
          intro a ha b hb
          have haeq : a =
              (factorRun rules hne x (boundaryCoefficient x y)).getLast
                (factorRun_ne_nil rules hne x (boundaryCoefficient x y)) := by
            rw [List.getLast?_eq_getLast_of_ne_nil
              (factorRun_ne_nil rules hne x (suffix x * nextPrefix (y :: ys)))] at ha
            simpa [nextPrefix, boundaryCoefficient] using ha.symm
          have hbeq : b =
              (factorRun rules hne y (suffix y * nextPrefix ys)).head
                (factorRun_ne_nil rules hne y (suffix y * nextPrefix ys)) := by
            rw [expansionTail] at hb
            rw [List.head?_append_of_ne_nil
              (factorRun rules hne y (suffix y * nextPrefix ys))
              (factorRun_ne_nil rules hne y (suffix y * nextPrefix ys))] at hb
            rw [List.head?_eq_some_head
              (factorRun_ne_nil rules hne y (suffix y * nextPrefix ys))] at hb
            simpa using hb.symm
          subst a
          subst b
          apply factor_boundary_rel rules hne x y
          exact (List.isChain_cons.1 hreduced).1 y (by simp)

/-- The product of the indicated same-sign stable letters in the two-HNN-extension group. -/
def stableProduct (colors : List (Fin 2)) (u : ℤˣ) :
    MultipleHNN.Extension A0 B0 phi0 :=
  (colors.map fun color ↦
    MultipleHNNFlat.stableLetter A0 B0 phi0 color ^ (u : ℤ)).prod

@[simp] theorem flat_baseEmbedding (g : BorisovHNNModel.Base) :
    MultipleHNN.baseEmbedding A0 B0 phi0 g = baseToG0HNN g := rfl

theorem flat_baseEmbedding_one :
    MultipleHNN.baseEmbedding A0 B0 phi0
      (1 : BorisovHNNModel.Base) = 1 :=
  map_one _

@[simp] theorem baseToG0HNN_d :
    baseToG0HNN BorisovHNNModel.d = hnnD := rfl

@[simp] theorem baseToG0HNN_e :
    baseToG0HNN BorisovHNNModel.e = hnnE := rfl

theorem flat_d_rulePower (i : Fin 3) :
    MultipleHNN.baseEmbedding A0 B0 phi0
        (BorisovHNNModel.d ^ rulePower i) = hnnD ^ (i.val + 1) := by
  rw [flat_baseEmbedding, map_zpow, baseToG0HNN_d]
  change hnnD ^ rulePower i = hnnD ^ (i.val + 1)
  rw [show rulePower i = ((i.val + 1 : ℕ) : ℤ) by simp [rulePower]]
  exact zpow_natCast _ _

theorem flat_e_rulePower (i : Fin 3) :
    MultipleHNN.baseEmbedding A0 B0 phi0
        (BorisovHNNModel.e ^ rulePower i) = hnnE ^ (i.val + 1) := by
  rw [flat_baseEmbedding, map_zpow, baseToG0HNN_e]
  change hnnE ^ rulePower i = hnnE ^ (i.val + 1)
  rw [show rulePower i = ((i.val + 1 : ℕ) : ℤ) by simp [rulePower]]
  exact zpow_natCast _ _

theorem run_eval (colors : List (Fin 2)) (hne : colors ≠ [])
    (u : ℤˣ) (lastCoeff : BorisovHNNModel.Base) :
    ((run colors hne u lastCoeff).map fun s ↦
      MultipleHNNFlat.stableLetter A0 B0 phi0 s.color ^ (s.sign : ℤ) *
        MultipleHNN.baseEmbedding A0 B0 phi0 s.coeff).prod =
      stableProduct colors u *
        MultipleHNN.baseEmbedding A0 B0 phi0 lastCoeff := by
  let letter : Fin 2 → MultipleHNN.Extension A0 B0 phi0 := fun color ↦
    MultipleHNNFlat.stableLetter A0 B0 phi0 color ^ (u : ℤ)
  have hletters :
      (colors.dropLast.map letter).prod * letter (colors.getLast hne) =
        stableProduct colors u := by
    unfold stableProduct
    change (colors.dropLast.map letter).prod * letter (colors.getLast hne) =
      (colors.map letter).prod
    calc
      _ = (colors.dropLast.map letter ++
          [letter (colors.getLast hne)]).prod := by
        rw [List.prod_append]
        simp
      _ = (colors.map letter).prod := by
        apply congrArg List.prod
        rw [← List.map_singleton, ← List.map_append,
          List.dropLast_append_getLast hne]
  rw [show run colors hne u lastCoeff =
      colors.dropLast.map (fun color ↦
        { color := color, sign := u, coeff := 1 }) ++
      [{ color := colors.getLast hne, sign := u, coeff := lastCoeff }] from rfl]
  rw [List.map_append, List.prod_append]
  simp only [List.map_map, List.map_singleton, List.prod_singleton]
  have hdrop :
      colors.dropLast.map
          ((fun s ↦
            MultipleHNNFlat.stableLetter A0 B0 phi0 s.color ^ (s.sign : ℤ) *
              MultipleHNN.baseEmbedding A0 B0 phi0 s.coeff) ∘
            fun color ↦ ({ color := color, sign := u, coeff := 1 } : FlatSyllable)) =
        colors.dropLast.map letter := by
    apply List.map_congr_left
    intro color _
    change MultipleHNNFlat.stableLetter A0 B0 phi0 color ^ (u : ℤ) *
        MultipleHNN.baseEmbedding A0 B0 phi0 1 = letter color
    rw [flat_baseEmbedding_one, mul_one]
  rw [hdrop]
  change (colors.dropLast.map letter).prod *
      (letter (colors.getLast hne) *
        MultipleHNN.baseEmbedding A0 B0 phi0 lastCoeff) =
    stableProduct colors u *
      MultipleHNN.baseEmbedding A0 B0 phi0 lastCoeff
  rw [← mul_assoc, hletters]

theorem stableProduct_one (colors : List (Fin 2)) :
    stableProduct colors 1 = modelPositive colors := by
  simp only [stableProduct, modelPositive, Thue.evalPositive]
  congr 1
  apply List.map_congr_left
  intro color hcolor
  fin_cases color <;> rfl

theorem stableProduct_reverse_neg_one (colors : List (Fin 2)) :
    stableProduct colors.reverse (-1) = (stableProduct colors 1)⁻¹ := by
  have hneg : ((-1 : ℤˣ) : ℤ) = -1 := by norm_num
  have hone : ((1 : ℤˣ) : ℤ) = 1 := by norm_num
  simp only [stableProduct, hneg, hone, zpow_neg, zpow_one]
  rw [List.prod_inv_reverse]
  rw [List.map_reverse]
  have hmap :
      colors.map (fun color ↦
          (MultipleHNNFlat.stableLetter A0 B0 phi0 color)⁻¹) =
        (colors.map fun color ↦
          MultipleHNNFlat.stableLetter A0 B0 phi0 color).map (fun x ↦ x⁻¹) := by
    rw [List.map_map]
    rfl
  rw [hmap]

theorem stableProduct_singleton_one (color : Fin 2) :
    stableProduct [color] 1 =
      MultipleHNNFlat.stableLetter A0 B0 phi0 color := by
  simp [stableProduct]

theorem stableProduct_singleton_neg_one (color : Fin 2) :
    stableProduct [color] (-1) =
      (MultipleHNNFlat.stableLetter A0 B0 phi0 color)⁻¹ := by
  have hneg : ((-1 : ℤˣ) : ℤ) = -1 := by norm_num
  simp [stableProduct, hneg]

theorem toHNN_stable_flat (beta : Fin 2) :
    toHNN (stable beta) =
      MultipleHNNFlat.stableLetter A0 B0 phi0 beta := by
  fin_cases beta <;> rfl

/-- The group element represented by the expansion of one signed basis letter. -/
def factorModel (rules : Fin 3 → List (Fin 2)) (x : Basis × Bool) :
    MultipleHNN.Extension A0 B0 phi0 :=
  MultipleHNN.baseEmbedding A0 B0 phi0 (factorPrefix x) *
    stableProduct (factorColors rules x) (signedUnit x.2) *
      MultipleHNN.baseEmbedding A0 B0 phi0 (suffix x)

theorem factorModel_positive_u (datum : Thue.StandingDatum) (q : Basis) :
    factorModel datum.F (q, true) = toHNN (uBasis datum q) := by
  cases q with
  | inl beta =>
      rw [factorModel, factorPrefix, suffix, factorColors, signedUnit_true,
        stableProduct_singleton_one, uBasis, toHNN_stable_flat]
      simp only [flat_baseEmbedding_one, one_mul, mul_one]
  | inr i =>
      rw [factorModel, factorPrefix, suffix, factorColors, signedUnit_true,
        stableProduct_one, flat_d_rulePower, flat_e_rulePower]
      change _ = toHNN (a datum i)
      exact (toHNN_a datum i).symm

theorem factorModel_positive_v (datum : Thue.StandingDatum) (q : Basis) :
    factorModel datum.E (q, true) = toHNN (vBasis datum q) := by
  cases q with
  | inl beta =>
      rw [factorModel, factorPrefix, suffix, factorColors, signedUnit_true,
        stableProduct_singleton_one, vBasis, toHNN_stable_flat]
      simp only [flat_baseEmbedding_one, one_mul, mul_one]
  | inr i =>
      rw [factorModel, factorPrefix, suffix, factorColors, signedUnit_true,
        stableProduct_one, flat_d_rulePower, flat_e_rulePower]
      change _ = toHNN (b datum i)
      exact (toHNN_b datum i).symm

theorem factorModel_negative
    (rules : Fin 3 → List (Fin 2)) (q : Basis) :
    factorModel rules (q, false) = (factorModel rules (q, true))⁻¹ := by
  cases q with
  | inl beta =>
      change
        MultipleHNN.baseEmbedding A0 B0 phi0 1 *
            stableProduct [beta] (-1) *
              MultipleHNN.baseEmbedding A0 B0 phi0 1 =
          (MultipleHNN.baseEmbedding A0 B0 phi0 1 *
              stableProduct [beta] 1 *
                MultipleHNN.baseEmbedding A0 B0 phi0 1)⁻¹
      rw [stableProduct_singleton_neg_one, stableProduct_singleton_one]
      simp only [flat_baseEmbedding_one]
      group
  | inr i =>
      change
        MultipleHNN.baseEmbedding A0 B0 phi0
              (BorisovHNNModel.e ^ (-rulePower i)) *
            stableProduct (rules i).reverse (-1) *
              MultipleHNN.baseEmbedding A0 B0 phi0
                (BorisovHNNModel.d ^ (-rulePower i)) =
          (MultipleHNN.baseEmbedding A0 B0 phi0
                (BorisovHNNModel.d ^ rulePower i) *
              stableProduct (rules i) 1 *
                MultipleHNN.baseEmbedding A0 B0 phi0
                  (BorisovHNNModel.e ^ rulePower i))⁻¹
      rw [stableProduct_reverse_neg_one]
      simp only [map_zpow, zpow_neg, map_inv]
      group

theorem factorModel_u (datum : Thue.StandingDatum) (x : Basis × Bool) :
    factorModel datum.F x =
      if x.2 then toHNN (uBasis datum x.1)
      else (toHNN (uBasis datum x.1))⁻¹ := by
  rcases x with ⟨q, sign⟩
  cases sign
  · rw [factorModel_negative, factorModel_positive_u]
    rfl
  · simpa using factorModel_positive_u datum q

theorem factorModel_v (datum : Thue.StandingDatum) (x : Basis × Bool) :
    factorModel datum.E x =
      if x.2 then toHNN (vBasis datum x.1)
      else (toHNN (vBasis datum x.1))⁻¹ := by
  rcases x with ⟨q, sign⟩
  cases sign
  · rw [factorModel_negative, factorModel_positive_v]
    rfl
  · simpa using factorModel_positive_v datum q

theorem factorRun_eval
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (x : Basis × Bool) (lastCoeff : BorisovHNNModel.Base) :
    ((factorRun rules hne x lastCoeff).map fun s ↦
      MultipleHNNFlat.stableLetter A0 B0 phi0 s.color ^ (s.sign : ℤ) *
        MultipleHNN.baseEmbedding A0 B0 phi0 s.coeff).prod =
      stableProduct (factorColors rules x) (signedUnit x.2) *
        MultipleHNN.baseEmbedding A0 B0 phi0 lastCoeff :=
  run_eval _ _ _ _

/-- The literal expansion evaluates to the product of its signed displayed
factors.  This is independent of reducedness. -/
theorem expansion_eval
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (letters : List (Basis × Bool)) :
    MultipleHNN.baseEmbedding A0 B0 phi0 (expansionHead letters) *
        ((expansionTail rules hne letters).map fun s ↦
          MultipleHNNFlat.stableLetter A0 B0 phi0 s.color ^ (s.sign : ℤ) *
            MultipleHNN.baseEmbedding A0 B0 phi0 s.coeff).prod =
      (letters.map (factorModel rules)).prod := by
  induction letters with
  | nil =>
      simp only [expansionHead, expansionTail, List.map_nil, List.prod_nil,
        flat_baseEmbedding_one, one_mul]
  | cons x xs ih =>
      rw [expansionHead, expansionTail, List.map_append, List.prod_append,
        factorRun_eval]
      cases xs with
      | nil =>
          simp only [nextPrefix, factorModel, expansionTail, List.map_nil,
            List.prod_nil, List.map_singleton, List.prod_singleton, mul_one]
          exact (mul_assoc _ _ _).symm
      | cons y ys =>
          simp only [expansionHead, List.map_cons, List.prod_cons] at ih ⊢
          rw [map_mul]
          rw [← ih]
          simp only [nextPrefix, factorModel]
          group

theorem expansionTail_ne_nil
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (letters : List (Basis × Bool)) (hletters : letters ≠ []) :
    expansionTail rules hne letters ≠ [] := by
  cases letters with
  | nil => exact (hletters rfl).elim
  | cons x xs =>
      intro happ
      have hfirst := (List.append_eq_nil_iff.mp happ).1
      exact factorRun_ne_nil rules hne x _ hfirst

/-- The flattened reduced-word expansion associated with the supplied rewriting rules. -/
def expansionWord
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (letters : List (Basis × Bool))
    (hreduced : letters.IsChain (fun x y ↦ x.1 = y.1 → x.2 = y.2)) :
    FlatWord where
  head := expansionHead letters
  toList := expansionTail rules hne letters
  chain := expansionTail_chain rules hne letters hreduced

theorem expansionWord_eval
    (rules : Fin 3 → List (Fin 2)) (hne : ∀ i, rules i ≠ [])
    (letters : List (Basis × Bool))
    (hreduced : letters.IsChain (fun x y ↦ x.1 = y.1 → x.2 = y.2)) :
    MultipleHNNFlat.eval A0 B0 phi0
        (expansionWord rules hne letters hreduced) =
      (letters.map (factorModel rules)).prod := by
  simpa [MultipleHNNFlat.eval, expansionWord] using
    expansion_eval rules hne letters

theorem factorProduct_u (datum : Thue.StandingDatum)
    (letters : List (Basis × Bool)) :
    (letters.map (factorModel datum.F)).prod =
      toHNN (FreeGroup.lift (uBasis datum) (FreeGroup.mk letters)) := by
  rw [FreeGroup.lift_mk, map_list_prod]
  congr 1
  rw [List.map_map]
  apply List.map_congr_left
  rintro ⟨q, sign⟩ _
  rw [factorModel_u]
  cases sign <;> simp <;> rfl

theorem factorProduct_v (datum : Thue.StandingDatum)
    (letters : List (Basis × Bool)) :
    (letters.map (factorModel datum.E)).prod =
      toHNN (FreeGroup.lift (vBasis datum) (FreeGroup.mk letters)) := by
  rw [FreeGroup.lift_mk, map_list_prod]
  congr 1
  rw [List.map_map]
  apply List.map_congr_left
  rintro ⟨q, sign⟩ _
  rw [factorModel_v]
  cases sign <;> simp <;> rfl

/-- The flattened expansion of a word in the left-rule basis. -/
def uExpansion (datum : Thue.StandingDatum) (w : FreeGroup Basis) : FlatWord :=
  expansionWord datum.F datum.F_nonempty w.toWord
    (FreeGroup.isReduced_toWord (x := w))

/-- The flattened expansion of a word in the right-rule basis. -/
def vExpansion (datum : Thue.StandingDatum) (w : FreeGroup Basis) : FlatWord :=
  expansionWord datum.E datum.E_nonempty w.toWord
    (FreeGroup.isReduced_toWord (x := w))

theorem uExpansion_eval (datum : Thue.StandingDatum) (w : FreeGroup Basis) :
    MultipleHNNFlat.eval A0 B0 phi0 (uExpansion datum w) =
      toHNN (FreeGroup.lift (uBasis datum) w) := by
  unfold uExpansion
  rw [expansionWord_eval datum.F datum.F_nonempty w.toWord
    (FreeGroup.isReduced_toWord (x := w)), factorProduct_u, FreeGroup.mk_toWord]

theorem vExpansion_eval (datum : Thue.StandingDatum) (w : FreeGroup Basis) :
    MultipleHNNFlat.eval A0 B0 phi0 (vExpansion datum w) =
      toHNN (FreeGroup.lift (vBasis datum) w) := by
  unfold vExpansion
  rw [expansionWord_eval datum.E datum.E_nonempty w.toWord
    (FreeGroup.isReduced_toWord (x := w)), factorProduct_v, FreeGroup.mk_toWord]

private theorem toWord_ne_nil_of_ne_one {w : FreeGroup Basis} (hw : w ≠ 1) :
    w.toWord ≠ [] := by
  intro hnil
  apply hw
  rw [← FreeGroup.mk_toWord (x := w), hnil]
  rfl

theorem uExpansion_toList_ne_nil (datum : Thue.StandingDatum)
    {w : FreeGroup Basis} (hw : w ≠ 1) :
    (uExpansion datum w).toList ≠ [] :=
  expansionTail_ne_nil datum.F datum.F_nonempty w.toWord
    (toWord_ne_nil_of_ne_one hw)

theorem vExpansion_toList_ne_nil (datum : Thue.StandingDatum)
    {w : FreeGroup Basis} (hw : w ≠ 1) :
    (vExpansion datum w).toList ≠ [] :=
  expansionTail_ne_nil datum.E datum.E_nonempty w.toWord
    (toWord_ne_nil_of_ne_one hw)

/-- A nontrivial free word has nontrivial image under the displayed
`A`-basis lift. -/
theorem uLift_ne_one (datum : Thue.StandingDatum) {w : FreeGroup Basis}
    (hw : w ≠ 1) : FreeGroup.lift (uBasis datum) w ≠ 1 := by
  have hflat := MultipleHNNFlat.eval_ne_one A0 B0 phi0
    (uExpansion datum w) (uExpansion_toList_ne_nil datum hw)
  intro hOne
  apply hflat
  rw [uExpansion_eval, hOne, map_one]
  rfl

/-- The corresponding nontriviality theorem for the displayed `B`-basis. -/
theorem vLift_ne_one (datum : Thue.StandingDatum) {w : FreeGroup Basis}
    (hw : w ≠ 1) : FreeGroup.lift (vBasis datum) w ≠ 1 := by
  have hflat := MultipleHNNFlat.eval_ne_one A0 B0 phi0
    (vExpansion datum w) (vExpansion_toList_ne_nil datum hw)
  intro hOne
  apply hflat
  rw [vExpansion_eval, hOne, map_one]
  rfl

/-- Borisov's first rank-five freeness assertion. -/
theorem uLift_injective (datum : Thue.StandingDatum) :
    Function.Injective (FreeGroup.lift (uBasis datum)) := by
  apply (injective_iff_map_eq_one _).2
  intro w hw
  by_contra hne
  exact uLift_ne_one datum hne hw

/-- Borisov's second rank-five freeness assertion. -/
theorem vLift_injective (datum : Thue.StandingDatum) :
    Function.Injective (FreeGroup.lift (vBasis datum)) := by
  apply (injective_iff_map_eq_one _).2
  intro w hw
  by_contra hne
  exact vLift_ne_one datum hne hw

/-- A nontrivial `A`-basis word does not land in the embedded base subgroup
`<d₃,e₃>`. -/
theorem uLift_not_mem_DE3_of_ne_one (datum : Thue.StandingDatum)
    {w : FreeGroup Basis} (hw : w ≠ 1) :
    toHNN (FreeGroup.lift (uBasis datum) w) ∉
      BorisovCStage.DE3 := by
  intro hmem
  have hflat := MultipleHNNFlat.eval_not_mem_base A0 B0 phi0
    (uExpansion datum w) (uExpansion_toList_ne_nil datum hw)
  apply hflat
  rw [uExpansion_eval]
  rw [BorisovBaseRange.DE3_eq_range_baseEmbedding] at hmem
  exact hmem

/-- A nontrivial `B`-basis word does not land in the embedded base subgroup
`<d₃,e₃>`. -/
theorem vLift_not_mem_DE3_of_ne_one (datum : Thue.StandingDatum)
    {w : FreeGroup Basis} (hw : w ≠ 1) :
    toHNN (FreeGroup.lift (vBasis datum) w) ∉
      BorisovCStage.DE3 := by
  intro hmem
  have hflat := MultipleHNNFlat.eval_not_mem_base A0 B0 phi0
    (vExpansion datum w) (vExpansion_toList_ne_nil datum hw)
  apply hflat
  rw [vExpansion_eval]
  rw [BorisovBaseRange.DE3_eq_range_baseEmbedding] at hmem
  exact hmem

theorem Uc_eq_uLift_range (datum : Thue.StandingDatum) :
    Uc datum = MonoidHom.range (FreeGroup.lift (uBasis datum)) := by
  unfold Uc
  rw [FreeGroup.range_lift_eq_closure]

theorem Vc_eq_vLift_range (datum : Thue.StandingDatum) :
    Vc datum = MonoidHom.range (FreeGroup.lift (vBasis datum)) := by
  unfold Vc
  rw [FreeGroup.range_lift_eq_closure]

/-- The complete Assertion IV package, including the letterwise
correspondence between the two free rank-five subgroups. -/
theorem assertionIV (datum : Thue.StandingDatum) : AssertionIV datum := by
  refine
    { u_free := uLift_injective datum
      v_free := vLift_injective datum
      correspondence := ?_ }
  let uEquiv : FreeGroup Basis ≃*
      MonoidHom.range (FreeGroup.lift (uBasis datum)) :=
    MonoidHom.ofInjective (uLift_injective datum)
  let vEquiv : FreeGroup Basis ≃*
      MonoidHom.range (FreeGroup.lift (vBasis datum)) :=
    MonoidHom.ofInjective (vLift_injective datum)
  let uCast : Uc datum ≃*
      MonoidHom.range (FreeGroup.lift (uBasis datum)) :=
    MulEquiv.subgroupCongr (Uc_eq_uLift_range datum)
  let vCast : Vc datum ≃*
      MonoidHom.range (FreeGroup.lift (vBasis datum)) :=
    MulEquiv.subgroupCongr (Vc_eq_vLift_range datum)
  let equiv : Uc datum ≃* Vc datum :=
    uCast.trans (uEquiv.symm.trans (vEquiv.trans vCast.symm))
  refine ⟨equiv, ?_⟩
  intro q
  have hu : uCast ⟨uBasis datum q, uBasis_mem_Uc datum q⟩ =
      uEquiv (FreeGroup.of q) := by
    ext
    rw [MonoidHom.ofInjective_apply]
    simp [uCast]
  have hv : vCast ⟨vBasis datum q, vBasis_mem_Vc datum q⟩ =
      vEquiv (FreeGroup.of q) := by
    ext
    rw [MonoidHom.ofInjective_apply]
    simp [vCast]
  change ((equiv ⟨uBasis datum q, uBasis_mem_Uc datum q⟩ : Vc datum) : G0) =
    vBasis datum q
  simp only [equiv, MulEquiv.trans_apply, hu, uEquiv.symm_apply_apply,
    ← hv, vCast.symm_apply_apply]

end

end BorisovAssertionIV
end Undecidability
