/-
Copyright (c) 2026 Lean Pool contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lean Pool contributors
-/
module  -- shake: keep-all --deprecated_module: ignore

-- Generated project imports; run `lake exe mk_all`.
public import LeanPool.JacobianDiffgeo
public import LeanPool.JacobianDiffgeo.Abel
public import LeanPool.JacobianDiffgeo.Abel.AreaPairing
public import LeanPool.JacobianDiffgeo.Abel.ChartSupported
public import LeanPool.JacobianDiffgeo.Abel.DolbeaultBridge
public import LeanPool.JacobianDiffgeo.Abel.LinkData
public import LeanPool.JacobianDiffgeo.Abel.LogPiece
public import LeanPool.JacobianDiffgeo.Abel.Loops
public import LeanPool.JacobianDiffgeo.Abel.OfCurveInj
public import LeanPool.JacobianDiffgeo.Abel.SerreFunctional
public import LeanPool.JacobianDiffgeo.Abel.Sufficiency
public import LeanPool.JacobianDiffgeo.Abel.UpgradeDischarge
public import LeanPool.JacobianDiffgeo.Abel.WeakToMero
public import LeanPool.JacobianDiffgeo.AbelWeak
public import LeanPool.JacobianDiffgeo.AbelWeak.ChainAssembly
public import LeanPool.JacobianDiffgeo.AbelWeak.GeneralChain
public import LeanPool.JacobianDiffgeo.AbelWeak.PlanarLogBranch
public import LeanPool.JacobianDiffgeo.AbelWeak.Rechart
public import LeanPool.JacobianDiffgeo.AbelWeak.SingleChart
public import LeanPool.JacobianDiffgeo.AbelWeak.WeakSolution
public import LeanPool.JacobianDiffgeo.CanonicalForms
public import LeanPool.JacobianDiffgeo.CanonicalForms.Differential
public import LeanPool.JacobianDiffgeo.CanonicalForms.Existence
public import LeanPool.JacobianDiffgeo.CanonicalForms.LinearSystems
public import LeanPool.JacobianDiffgeo.CanonicalForms.MForm
public import LeanPool.JacobianDiffgeo.CanonicalForms.OneDimensional
public import LeanPool.JacobianDiffgeo.CanonicalForms.OrdRes
public import LeanPool.JacobianDiffgeo.CanonicalForms.Quotient
public import LeanPool.JacobianDiffgeo.Cech
public import LeanPool.JacobianDiffgeo.Cech.Cochains
public import LeanPool.JacobianDiffgeo.Cech.Colimit
public import LeanPool.JacobianDiffgeo.Cech.Covers
public import LeanPool.JacobianDiffgeo.Cech.H0
public import LeanPool.JacobianDiffgeo.Cech.Injectivity
public import LeanPool.JacobianDiffgeo.Cech.Refinement
public import LeanPool.JacobianDiffgeo.Cech.SixTerm
public import LeanPool.JacobianDiffgeo.Cech.Skyscraper
public import LeanPool.JacobianDiffgeo.Cech.Window
public import LeanPool.JacobianDiffgeo.Cech.WindowRank
public import LeanPool.JacobianDiffgeo.CechCount
public import LeanPool.JacobianDiffgeo.CechCount.Count
public import LeanPool.JacobianDiffgeo.CechCount.Final
public import LeanPool.JacobianDiffgeo.CechCount.Mul
public import LeanPool.JacobianDiffgeo.CechCount.Surjective
public import LeanPool.JacobianDiffgeo.Challenge
public import LeanPool.JacobianDiffgeo.Dbar
public import LeanPool.JacobianDiffgeo.Dbar.CauchyKernel
public import LeanPool.JacobianDiffgeo.Dbar.DiskAcyclic
public import LeanPool.JacobianDiffgeo.Dbar.Form01
public import LeanPool.JacobianDiffgeo.Dbar.Operator
public import LeanPool.JacobianDiffgeo.Dbar.PlanarCousin
public import LeanPool.JacobianDiffgeo.Dbar.PlanarPoU
public import LeanPool.JacobianDiffgeo.Dbar.SolveDisk
public import LeanPool.JacobianDiffgeo.Dbar.Wirtinger
public import LeanPool.JacobianDiffgeo.DolbeaultComparison
public import LeanPool.JacobianDiffgeo.DolbeaultComparison.Comparison
public import LeanPool.JacobianDiffgeo.DolbeaultComparison.GlueForm01
public import LeanPool.JacobianDiffgeo.DolbeaultComparison.Leray
public import LeanPool.JacobianDiffgeo.DolbeaultComparison.Splitting
public import LeanPool.JacobianDiffgeo.Finiteness
public import LeanPool.JacobianDiffgeo.Finiteness.BddHolo
public import LeanPool.JacobianDiffgeo.Finiteness.Chain
public import LeanPool.JacobianDiffgeo.Finiteness.Chi
public import LeanPool.JacobianDiffgeo.Finiteness.CompactRestrict
public import LeanPool.JacobianDiffgeo.Finiteness.H1Finite
public import LeanPool.JacobianDiffgeo.Finiteness.Schwartz
public import LeanPool.JacobianDiffgeo.Finiteness.TradeBounded
public import LeanPool.JacobianDiffgeo.FormTrace
public import LeanPool.JacobianDiffgeo.FormTrace.PairForm
public import LeanPool.JacobianDiffgeo.FormTrace.ResidueTraceCompat
public import LeanPool.JacobianDiffgeo.FormTrace.TraceZkForm
public import LeanPool.JacobianDiffgeo.Forms
public import LeanPool.JacobianDiffgeo.Forms.Analyticity
public import LeanPool.JacobianDiffgeo.Forms.Basic
public import LeanPool.JacobianDiffgeo.Forms.Coeffs
public import LeanPool.JacobianDiffgeo.Forms.Finiteness
public import LeanPool.JacobianDiffgeo.Forms.Genus
public import LeanPool.JacobianDiffgeo.Forms.MDifferential
public import LeanPool.JacobianDiffgeo.Forms.Montel
public import LeanPool.JacobianDiffgeo.Forms.OfCoeffs
public import LeanPool.JacobianDiffgeo.GenusSphereHeadline
public import LeanPool.JacobianDiffgeo.GenusSphereHeadline.Basic
public import LeanPool.JacobianDiffgeo.H1Genus
public import LeanPool.JacobianDiffgeo.H1Genus.Basic
public import LeanPool.JacobianDiffgeo.Init
public import LeanPool.JacobianDiffgeo.JacFunctorial
public import LeanPool.JacobianDiffgeo.JacFunctorial.Challenge
public import LeanPool.JacobianDiffgeo.JacFunctorial.ChallengeLaws
public import LeanPool.JacobianDiffgeo.JacFunctorial.Density
public import LeanPool.JacobianDiffgeo.JacFunctorial.PeriodMaps
public import LeanPool.JacobianDiffgeo.JacFunctorial.Pullback
public import LeanPool.JacobianDiffgeo.JacFunctorial.PullbackIntegral
public import LeanPool.JacobianDiffgeo.JacFunctorial.PullbackMaps
public import LeanPool.JacobianDiffgeo.JacFunctorial.Trace
public import LeanPool.JacobianDiffgeo.JacFunctorial.TraceCoeff
public import LeanPool.JacobianDiffgeo.JacFunctorial.TraceIntegral
public import LeanPool.JacobianDiffgeo.JacFunctorial.TraceLaws
public import LeanPool.JacobianDiffgeo.JacobianConstruction
public import LeanPool.JacobianDiffgeo.JacobianConstruction.Basic
public import LeanPool.JacobianDiffgeo.JacobianConstruction.ChartedSpaceKitV
public import LeanPool.JacobianDiffgeo.JacobianConstruction.Functorial
public import LeanPool.JacobianDiffgeo.JacobianConstruction.OfCurve
public import LeanPool.JacobianDiffgeo.JacobianConstruction.Periods
public import LeanPool.JacobianDiffgeo.JacobianConstruction.Torus
public import LeanPool.JacobianDiffgeo.JacobianConstruction.ULift
public import LeanPool.JacobianDiffgeo.LaurentTail
public import LeanPool.JacobianDiffgeo.LaurentTail.Comparison
public import LeanPool.JacobianDiffgeo.LaurentTail.RiemannRoch
public import LeanPool.JacobianDiffgeo.LaurentTail.TailSpace
public import LeanPool.JacobianDiffgeo.LaurentTail.Truncation
public import LeanPool.JacobianDiffgeo.LocalMultiplicity
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.AdaptedCharts
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.ChartBridge
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.Composition
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.KthRoot
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.Multiplicity
public import LeanPool.JacobianDiffgeo.LocalMultiplicity.PlanarNormalForm
public import LeanPool.JacobianDiffgeo.MappingDegree
public import LeanPool.JacobianDiffgeo.MappingDegree.Basics
public import LeanPool.JacobianDiffgeo.MappingDegree.Covering
public import LeanPool.JacobianDiffgeo.MappingDegree.Degree
public import LeanPool.JacobianDiffgeo.MappingDegree.LocalConstancy
public import LeanPool.JacobianDiffgeo.MappingDegree.LocalStructure
public import LeanPool.JacobianDiffgeo.MappingDegree.Ramification
public import LeanPool.JacobianDiffgeo.MappingDegree.RootCounting
public import LeanPool.JacobianDiffgeo.Meromorphic
public import LeanPool.JacobianDiffgeo.Meromorphic.CodiscreteBridge
public import LeanPool.JacobianDiffgeo.Meromorphic.Divisor
public import LeanPool.JacobianDiffgeo.Meromorphic.Field
public import LeanPool.JacobianDiffgeo.Meromorphic.GermSpace
public import LeanPool.JacobianDiffgeo.Meromorphic.Gluing
public import LeanPool.JacobianDiffgeo.Meromorphic.LinSysMulEquiv
public import LeanPool.JacobianDiffgeo.Meromorphic.LinearSystem
public import LeanPool.JacobianDiffgeo.Meromorphic.OrderEval
public import LeanPool.JacobianDiffgeo.Meromorphic.Predicates
public import LeanPool.JacobianDiffgeo.MeromorphicTrace
public import LeanPool.JacobianDiffgeo.MeromorphicTrace.ArgumentPrinciple
public import LeanPool.JacobianDiffgeo.MeromorphicTrace.FunctionTrace
public import LeanPool.JacobianDiffgeo.MeromorphicTrace.OrderMultiplicity
public import LeanPool.JacobianDiffgeo.MeromorphicTrace.PlanarTrace
public import LeanPool.JacobianDiffgeo.MeromorphicTrace.ToP1
public import LeanPool.JacobianDiffgeo.Monodromy
public import LeanPool.JacobianDiffgeo.Monodromy.LogContinuation
public import LeanPool.JacobianDiffgeo.Monodromy.OpenLocus
public import LeanPool.JacobianDiffgeo.Path
public import LeanPool.JacobianDiffgeo.Path.Bridge
public import LeanPool.JacobianDiffgeo.Path.Chain
public import LeanPool.JacobianDiffgeo.Path.Continuation
public import LeanPool.JacobianDiffgeo.Path.HomotopySquare
public import LeanPool.JacobianDiffgeo.Path.LocalPrimitive
public import LeanPool.JacobianDiffgeo.Path.Periods
public import LeanPool.JacobianDiffgeo.Path.Perturb
public import LeanPool.JacobianDiffgeo.Path.Planar
public import LeanPool.JacobianDiffgeo.PeriodLattice
public import LeanPool.JacobianDiffgeo.PeriodLattice.Discreteness
public import LeanPool.JacobianDiffgeo.PeriodLattice.FormIdentity
public import LeanPool.JacobianDiffgeo.PeriodLattice.FullRank
public import LeanPool.JacobianDiffgeo.PeriodLattice.GenericPoints
public import LeanPool.JacobianDiffgeo.PeriodLattice.Membership
public import LeanPool.JacobianDiffgeo.PeriodLattice.Nondegeneracy
public import LeanPool.JacobianDiffgeo.PeriodLattice.Segment
public import LeanPool.JacobianDiffgeo.PlanarStokes
public import LeanPool.JacobianDiffgeo.PlanarStokes.AnnulusResidue
public import LeanPool.JacobianDiffgeo.PlanarStokes.CompactSupport
public import LeanPool.JacobianDiffgeo.PlanarStokes.Compat
public import LeanPool.JacobianDiffgeo.ProjectiveLine
public import LeanPool.JacobianDiffgeo.ProjectiveLine.Charts
public import LeanPool.JacobianDiffgeo.ProjectiveLine.GenusZero
public import LeanPool.JacobianDiffgeo.ProjectiveLine.Holomorphy
public import LeanPool.JacobianDiffgeo.ProjectiveLine.Inversion
public import LeanPool.JacobianDiffgeo.ProjectiveLine.Sphere
public import LeanPool.JacobianDiffgeo.ProperDegree
public import LeanPool.JacobianDiffgeo.ProperDegree.ChallengeDegree
public import LeanPool.JacobianDiffgeo.ProperDegree.DivisorDegreeZero
public import LeanPool.JacobianDiffgeo.ProperDegree.GenusZeroFinisher
public import LeanPool.JacobianDiffgeo.ResidueCalculus
public import LeanPool.JacobianDiffgeo.ResidueCalculus.ChangeOfVariables
public import LeanPool.JacobianDiffgeo.ResidueCalculus.GermFunctionals
public import LeanPool.JacobianDiffgeo.ResidueCalculus.IntegralBridge
public import LeanPool.JacobianDiffgeo.ResidueCalculus.LaurentCoeff
public import LeanPool.JacobianDiffgeo.ResidueCalculus.MittagLeffler
public import LeanPool.JacobianDiffgeo.ResidueCalculus.PrincipalPart
public import LeanPool.JacobianDiffgeo.ResidueCalculus.Residue
public import LeanPool.JacobianDiffgeo.ResidueCalculus.TaylorCoeff
public import LeanPool.JacobianDiffgeo.ResidueTheorem
public import LeanPool.JacobianDiffgeo.ResidueTheorem.Calibrated
public import LeanPool.JacobianDiffgeo.ResidueTheorem.MFormCompat
public import LeanPool.JacobianDiffgeo.ResidueTheorem.P1Assembly
public import LeanPool.JacobianDiffgeo.ResidueTheorem.RationalOnP1
public import LeanPool.JacobianDiffgeo.ResidueTheorem.Reduction
public import LeanPool.JacobianDiffgeo.ResidueTheorem.Unconditional
public import LeanPool.JacobianDiffgeo.RiemannRoch
public import LeanPool.JacobianDiffgeo.RiemannRoch.Basic
public import LeanPool.JacobianDiffgeo.SerrePairing
public import LeanPool.JacobianDiffgeo.SerrePairing.Duality
public import LeanPool.JacobianDiffgeo.SerrePairing.Pairing
public import LeanPool.JacobianDiffgeo.SerrePairing.TailSpace
public import LeanPool.JacobianDiffgeo.SphereTopology
public import LeanPool.JacobianDiffgeo.SphereTopology.GlobalPrimitive
public import LeanPool.JacobianDiffgeo.SphereTopology.Headline
public import LeanPool.JacobianDiffgeo.SphereTopology.SimplyConnectedP1
public import LeanPool.JacobianDiffgeo.Surface
public import LeanPool.JacobianDiffgeo.Surface.Bridges
public import LeanPool.JacobianDiffgeo.Surface.ChartedSpaceKit
public import LeanPool.JacobianDiffgeo.Surface.Identity
public import LeanPool.JacobianDiffgeo.Surface.InverseFunction
public import LeanPool.JacobianDiffgeo.Surface.RealSmooth
public import LeanPool.JacobianDiffgeo.TailDuality
public import LeanPool.JacobianDiffgeo.TailDuality.ChiLedger
public import LeanPool.JacobianDiffgeo.TailDuality.Counting
public import LeanPool.JacobianDiffgeo.TailDuality.Duality
public import LeanPool.JacobianDiffgeo.TailDuality.Pairing
public import LeanPool.JacobianDiffgeo.TailDuality.TailOps
