/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import LeanPool.SmallUndecidableGroups.Borisov.Model.CStage
public import LeanPool.SmallUndecidableGroups.GroupTheory.HNNLemmas

/-!
# ContextNormalForm

Part of the dependency closure of the small undecidable group constructions.
-/

@[expose] public section

namespace Undecidability
namespace BorisovContextNormalForm

open HNNLemmas
open BorisovCStage
open BorisovHNNModel

noncomputable section

/-- The two base-intersection statements from Lemma 3.5 of the paper, in the
iterated-HNN model.  They imply the compatibility needed to restrict the
`c`-HNN extension to the cyclic subgroups generated by `d` and by `e`. -/
structure BaseIntersections (datum : Thue.StandingDatum) : Prop where
  u_inf_DE : U datum ⊓ DE3 = ⊥
  v_inf_DE : V datum ⊓ DE3 = ⊥

private theorem element_eq_one_of_mem_inf_bot
    {G : Type*} [Group G] {H K : Subgroup G}
    (hinter : H ⊓ K = ⊥) {x : G} (hxH : x ∈ H) (hxK : x ∈ K) :
    x = 1 := by
  have hx : x ∈ (⊥ : Subgroup G) := by
    rw [← hinter]
    exact ⟨hxH, hxK⟩
  simpa using hx

private theorem cEquiv_preserves_dCyclic
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (a : U datum) :
    (a : Gamma3) ∈ dCyclic ↔
      (cEquiv datum hfree a : Gamma3) ∈ dCyclic := by
  constructor
  · intro ha
    have ha1 : (a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.u_inf_DE a.property
        (dCyclic_le_DE3 ha)
    have ha' : a = 1 := Subtype.ext ha1
    subst a
    simp
  · intro hpa
    have hpa1 : (cEquiv datum hfree a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.v_inf_DE
        (cEquiv datum hfree a).property (dCyclic_le_DE3 hpa)
    have hpa' : cEquiv datum hfree a = 1 := Subtype.ext hpa1
    have ha' : a = 1 := (cEquiv datum hfree).injective (by simpa using hpa')
    subst a
    simp

/-- The attaching equivalence for the `c`-stage preserves the cyclic
subgroup generated by `d`.  This is the compatibility needed for the exact
restricted-HNN presentation of `⟨d,c⟩`. -/
theorem cEquiv_mem_dCyclic_iff
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (a : U datum) :
    (a : Gamma3) ∈ dCyclic ↔
      (cEquiv datum hfree a : Gamma3) ∈ dCyclic :=
  cEquiv_preserves_dCyclic datum hfree hinter a

private theorem cEquiv_preserves_eCyclic
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (a : U datum) :
    (a : Gamma3) ∈ eCyclic ↔
      (cEquiv datum hfree a : Gamma3) ∈ eCyclic := by
  constructor
  · intro ha
    have ha1 : (a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.u_inf_DE a.property
        (eCyclic_le_DE3 ha)
    have ha' : a = 1 := Subtype.ext ha1
    subst a
    simp
  · intro hpa
    have hpa1 : (cEquiv datum hfree a : Gamma3) = 1 :=
      element_eq_one_of_mem_inf_bot hinter.v_inf_DE
        (cEquiv datum hfree a).property (eCyclic_le_DE3 hpa)
    have hpa' : cEquiv datum hfree a = 1 := Subtype.ext hpa1
    have ha' : a = 1 := (cEquiv datum hfree).injective (by simpa using hpa')
    subst a
    simp

private theorem CD_le_generatedWithStable_d
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    CD datum hfree ≤
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic := by
  rw [CD, Subgroup.closure_le]
  intro x hx
  rcases hx with hx | hx
  · have hc : x = c datum hfree := by simpa using hx
    subst x
    have ht : (HNNExtension.t : Gamma2 datum hfree) ∈
        generatedWithStable
          (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic := by
      apply Subgroup.subset_closure
      exact Or.inr rfl
    simpa [c] using
      (generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) dCyclic).inv_mem ht
  · have hd : x = of3 datum hfree d3 := by simpa using hx
    subst x
    apply Subgroup.subset_closure
    apply Or.inl
    exact ⟨d3, Subgroup.subset_closure (by simp), rfl⟩

/-- The subgroup `CD = ⟨c,d⟩` is exactly the restricted `c`-HNN
subgroup over the cyclic base `⟨d⟩`. -/
theorem CD_eq_generatedWithStable_d
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    CD datum hfree =
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree)
        dCyclic := by
  apply le_antisymm
  · exact CD_le_generatedWithStable_d datum hfree
  · rw [generatedWithStable, Subgroup.closure_le]
    intro x hx
    rcases hx with hx | hx
    · rcases hx with ⟨a, ha, rfl⟩
      let K : Subgroup Gamma3 := (CD datum hfree).comap (of3 datum hfree)
      have hdK : dCyclic ≤ K := by
        rw [dCyclic, Subgroup.closure_le, Set.singleton_subset_iff]
        change of3 datum hfree d3 ∈ CD datum hfree
        apply Subgroup.subset_closure
        simp
      exact hdK ha
    · rw [Set.mem_singleton_iff] at hx
      subst x
      have hc : c datum hfree ∈ CD datum hfree := by
        apply Subgroup.subset_closure
        simp
      simpa [c] using (CD datum hfree).inv_mem hc

/-- The exact restricted-HNN parameter group for `CD = ⟨d,c⟩`. -/
abbrev DRestricted
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) :=
  HNNExtension dCyclic
    (restrictedA (A := U datum) dCyclic)
    (restrictedB (B := V datum) dCyclic)
    (restrictedPhi dCyclic (cEquiv_mem_dCyclic_iff datum hfree hinter))

/-- Exact subgroup-presentation equivalence for `CD = ⟨d,c⟩`. -/
def dRestrictedEquivCD
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) :
    DRestricted datum hfree hinter ≃* CD datum hfree :=
  (restrictedEquivGeneratedWithStable dCyclic
      (cEquiv_mem_dCyclic_iff datum hfree hinter)).trans
    (MulEquiv.subgroupCongr
      (CD_eq_generatedWithStable_d datum hfree).symm)

@[simp] theorem dRestrictedEquivCD_of_coe
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) (x : dCyclic) :
    ((dRestrictedEquivCD datum hfree hinter (HNNExtension.of x) :
        CD datum hfree) : Gamma2 datum hfree) =
      of3 datum hfree (x : Gamma3) := by
  change
    ((restrictedEquivGeneratedWithStable dCyclic
        (cEquiv_mem_dCyclic_iff datum hfree hinter)
        (HNNExtension.of x) :
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree)
        dCyclic) : Gamma2 datum hfree) = _
  exact restrictedEquivGeneratedWithStable_coe dCyclic
    (cEquiv_mem_dCyclic_iff datum hfree hinter) (HNNExtension.of x)

@[simp] theorem dRestrictedEquivCD_t_coe
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) :
    ((dRestrictedEquivCD datum hfree hinter
        (HNNExtension.t : DRestricted datum hfree hinter) :
      CD datum hfree) : Gamma2 datum hfree) = HNNExtension.t := by
  change
    ((restrictedEquivGeneratedWithStable dCyclic
        (cEquiv_mem_dCyclic_iff datum hfree hinter)
        (HNNExtension.t : DRestricted datum hfree hinter) :
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree)
        dCyclic) : Gamma2 datum hfree) = _
  exact restrictedEquivGeneratedWithStable_coe dCyclic
    (cEquiv_mem_dCyclic_iff datum hfree hinter)
      (HNNExtension.t : DRestricted datum hfree hinter)

theorem dRestrictedEquivCD_inv_t_coe
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) :
    ((dRestrictedEquivCD datum hfree hinter
        ((HNNExtension.t : DRestricted datum hfree hinter)⁻¹) :
      CD datum hfree) : Gamma2 datum hfree) = c datum hfree := by
  rw [map_inv]
  change
    (((dRestrictedEquivCD datum hfree hinter
        (HNNExtension.t : DRestricted datum hfree hinter) :
      CD datum hfree) : Gamma2 datum hfree))⁻¹ = _
  rw [dRestrictedEquivCD_t_coe]
  rfl

private theorem CE_le_generatedWithStable_e
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    CE datum hfree ≤
      generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic := by
  rw [CE, Subgroup.closure_le]
  intro x hx
  rcases hx with hx | hx
  · have hc : x = c datum hfree := by simpa using hx
    subst x
    have ht : (HNNExtension.t : Gamma2 datum hfree) ∈
        generatedWithStable
          (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic := by
      apply Subgroup.subset_closure
      exact Or.inr rfl
    simpa [c] using
      (generatedWithStable
        (A := U datum) (B := V datum) (phi := cEquiv datum hfree) eCyclic).inv_mem ht
  · have he : x = of3 datum hfree e3 := by simpa using hx
    subst x
    apply Subgroup.subset_closure
    apply Or.inl
    exact ⟨e3, Subgroup.subset_closure (by simp), rfl⟩

/-- Every element of `<c,d>` has the irreducible left-context form used in
Borisov's Lemma 4. -/
theorem exists_leftContext_of_mem_CD
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) {x : Gamma2 datum hfree}
    (hx : x ∈ CD datum hfree) :
    ∃ L : LeftContext datum hfree, leftValue datum hfree L = x := by
  have hx' := CD_le_generatedWithStable_d datum hfree hx
  rcases exists_reducedWord_of_mem_generatedWithStable dCyclic
      (cEquiv_preserves_dCyclic datum hfree hinter) hx' with
    ⟨w, hw, hhead, hcoeff⟩
  exact ⟨⟨w, hhead, hcoeff⟩, hw⟩

/-- Every element of `<c,e>` has the irreducible right-context form used in
Borisov's Lemma 4. -/
theorem exists_rightContext_of_mem_CE
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum) {x : Gamma2 datum hfree}
    (hx : x ∈ CE datum hfree) :
    ∃ R : RightContext datum hfree, rightValue datum hfree R = x := by
  have hx' := CE_le_generatedWithStable_e datum hfree hx
  rcases exists_reducedWord_of_mem_generatedWithStable eCyclic
      (cEquiv_preserves_eCyclic datum hfree hinter) hx' with
    ⟨w, hw, hhead, hcoeff⟩
  exact ⟨⟨w, hhead, hcoeff⟩, hw⟩

end

end BorisovContextNormalForm
end Undecidability
