/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import LeanPool.SmallUndecidableGroups.GroupTheory.CommutatorLemmas
public import LeanPool.SmallUndecidableGroups.GroupTheory.HNNLemmas
public import LeanPool.SmallUndecidableGroups.Borisov.Model.ContextNormalForm

/-!
# ConverseCore

Part of the dependency closure of the small undecidable group constructions.
-/

@[expose] public section

namespace Undecidability

open CommutatorLemmas

namespace BorisovDoubleCosetBridge

open HNNLemmas

variable {G : Type*} [Group G]

/-- Sharp form of the last two HNN reductions in Borisov's converse.

The last stable letter `k` centralizes the subgroup generated by the image of
`A` and `P⁻¹tP`.  If `Q⁻¹tQ` commutes with `k`, comparison of the first
stable-letter coefficient gives the ordered double-coset equation
`P = c * Q * a`, with `c ∈ C` and `a ∈ A`. -/
theorem lastTwoStages_force_doubleCoset
    (A C : Subgroup G) (P Q : G)
    (hcomm : Commute
      (centralizerOf
        (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P))
        (conjugatedStable C Q))
      (centralizerStable
        (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)))) :
    ∃ c : C, ∃ a : A, P = (c : G) * Q * (a : G) := by
  let K : Subgroup (CentralizerHNN G C) :=
    generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)
  have hmem : conjugatedStable C Q ∈ K :=
    (centralizerOf_commute_stable_iff K (conjugatedStable C Q)).mp (by
      simpa [K] using hcomm)
  exact conjugatedStable_mem_generatedWith_imp_doubleCoset A C P Q hmem

/-- The same result for the commutator convention used by `Borisov.testWord`.
-/
theorem lastTwoStages_force_doubleCoset_of_commutator
    (A C : Subgroup G) (P Q : G)
    (hcommutator :
      (centralizerOf
          (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P))
          (conjugatedStable C Q))⁻¹ *
        (centralizerStable
          (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)))⁻¹ *
        centralizerOf
          (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P))
          (conjugatedStable C Q) *
        centralizerStable
          (generatedWith (A.map (centralizerOf C)) (conjugatedStable C P)) = 1) :
    ∃ c : C, ∃ a : A, P = (c : G) * Q * (a : G) := by
  apply lastTwoStages_force_doubleCoset A C P Q
  exact (inverse_commutator_eq_one_iff_commute _ _).mp hcommutator

end BorisovDoubleCosetBridge
end Undecidability

namespace Undecidability
namespace BorisovConverseCore

open HNNLemmas
open BorisovCStage
open BorisovContextNormalForm
open BorisovDoubleCosetBridge

noncomputable section

/-- The `t`-stage of Borisov's model, with `t` centralizing `<c,d>`. -/
abbrev TStage (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :=
  CentralizerHNN (Gamma2 datum hfree) (CD datum hfree)

/-- The inclusion into the HNN extension adjoining the generator `t`. -/
def toTStage (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    Gamma2 datum hfree →* TStage datum hfree :=
  centralizerOf (CD datum hfree)

/-- The new stable letter `t` in its centralizer HNN extension. -/
def tLetter (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    TStage datum hfree :=
  centralizerStable (CD datum hfree)

/-- The conjugate of `t` by the evaluated positive binary word. -/
def conjugatedT (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (w : List (Fin 2)) : TStage datum hfree :=
  conjugatedStable (CD datum hfree) (positive2 datum hfree w)

/-- The subgroup centralized by Borisov's final letter `k`. -/
def KSubgroup (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    Subgroup (TStage datum hfree) :=
  generatedWith
    ((CE datum hfree).map (toTStage datum hfree))
    (conjugatedT datum hfree datum.P)

/-- The final `k`-stage of the semantic HNN model. -/
abbrev FinalStage (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :=
  CentralizerHNN (TStage datum hfree) (KSubgroup datum hfree)

/-- The inclusion into the final HNN extension adjoining the generator `k`. -/
def toFinalStage (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    TStage datum hfree →* FinalStage datum hfree :=
  centralizerOf (KSubgroup datum hfree)

/-- The conjugated test element carried into the final HNN extension. -/
def finalConjugatedT (datum : Thue.StandingDatum)
    (hfree : RankFiveFree datum) (w : List (Fin 2)) :
    FinalStage datum hfree :=
  toFinalStage datum hfree (conjugatedT datum hfree w)

/-- The final stable letter `k`. -/
def kLetter (datum : Thue.StandingDatum) (hfree : RankFiveFree datum) :
    FinalStage datum hfree :=
  centralizerStable (KSubgroup datum hfree)

/-- Ordered double-coset factorization in the `c`-stage produces the exact
irreducible equation consumed by Borisov's Lemma 4. -/
theorem thueEq_of_context_factorization
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum)
    (hlemma4 : BorisovLemma4 datum hfree)
    (Q : List (Fin 2))
    (hfactor : ∃ l : CD datum hfree, ∃ r : CE datum hfree,
      positive2 datum hfree datum.P =
        (l : Gamma2 datum hfree) * positive2 datum hfree Q *
          (r : Gamma2 datum hfree)) :
    ThueEq (Thue.systemOf datum.F datum.E) Q datum.P := by
  rcases hfactor with ⟨l, r, hfactor⟩
  rcases exists_leftContext_of_mem_CD datum hfree hinter l.property with
    ⟨L, hL⟩
  rcases exists_rightContext_of_mem_CE datum hfree hinter r.property with
    ⟨R, hR⟩
  apply hlemma4 datum.P Q L R
  apply (equation_iff_factorization _ _ _ _).mpr
  simpa [hL, hR] using hfactor

/-- Fully formal last-two-stage implication.  Once Assertions IV--V provide
the base intersections and the local Lemma-4 induction, triviality of the
test commutator in the semantic HNN model implies the desired Thue equality.
-/
theorem model_test_eq_one_imp_thueEq
    (datum : Thue.StandingDatum) (hfree : RankFiveFree datum)
    (hinter : BaseIntersections datum)
    (hlemma4 : BorisovLemma4 datum hfree)
    (Q : List (Fin 2))
    (htest :
      (finalConjugatedT datum hfree Q)⁻¹ *
          (kLetter datum hfree)⁻¹ *
          finalConjugatedT datum hfree Q * kLetter datum hfree = 1) :
    ThueEq (Thue.systemOf datum.F datum.E) Q datum.P := by
  apply thueEq_of_context_factorization datum hfree hinter hlemma4 Q
  exact lastTwoStages_force_doubleCoset_of_commutator
    (CE datum hfree) (CD datum hfree)
    (positive2 datum hfree datum.P) (positive2 datum hfree Q) (by
      change
        (centralizerOf (KSubgroup datum hfree)
          (conjugatedStable (CD datum hfree)
            (positive2 datum hfree Q)))⁻¹ *
          (centralizerStable (KSubgroup datum hfree))⁻¹ *
          centralizerOf (KSubgroup datum hfree)
            (conjugatedStable (CD datum hfree)
              (positive2 datum hfree Q)) *
          centralizerStable (KSubgroup datum hfree) = 1 at htest
      exact htest)

end

end BorisovConverseCore
end Undecidability
