/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import LeanPool.SmallUndecidableGroups.Thue
public import Mathlib.Data.Fin.VecNotation

/-!
This file derives the canonical reduced-word consequences of Borisov's
Assertions IV--V and proves the four subgroup intersections in Lemma 3.5 of
the paper.

The normal-form input is stated for canonical reduced words in the displayed
free bases.  A rule-basis letter is declared to use both stable letters; this
is exactly where `StandingDatum.F_support` and `StandingDatum.E_support` enter
the paper proof.  Assertion V, followed by comparison of multiple-HNN normal
forms, says that a basis word representing an element of `J beta` cannot use
the other stable letter, and one representing an element of `<d,e>` cannot
use either stable letter.
-/

@[expose] public section

namespace Undecidability
namespace BorisovIntersections

/-- Words on the four generators `d, e, s₁, s₂` of the initial Borisov stage. -/
abbrev G0Word := Word 4

/-- Generator order at the first Borisov stage: `d,e,s1,s2`. -/
def dWord : G0Word := Word.generator 0
/-- The one-letter word representing `e`. -/
def eWord : G0Word := Word.generator 1
/-- The one-letter word representing the first stable generator. -/
def s1Word : G0Word := Word.generator 2
/-- The one-letter word representing the second stable generator. -/
def s2Word : G0Word := Word.generator 3

/-- The word representing the stable generator with the selected color. -/
def stableWord (beta : Fin 2) : G0Word :=
  if beta = 0 then s1Word else s2Word

/-- Substitute the two stable-generator words into a positive binary word. -/
def positiveWord (w : List (Fin 2)) : G0Word :=
  Word.substitutePositive s1Word s2Word w

/-- The relator imposing `s⁻¹ * d⁴ * s = d`. -/
def sDRelator (s : G0Word) : G0Word :=
  Word.relation (Word.product [Word.inverse s, Word.pow dWord 4, s]) dWord

/-- The relator imposing `s⁻¹ * e * s = e⁴`. -/
def sERelator (s : G0Word) : G0Word :=
  Word.relation (Word.product [Word.inverse s, eWord, s]) (Word.pow eWord 4)

/-- The four-generator, four-relator first stage `G0`, corresponding to
`Γ₁` in equation (1) of the paper. -/
def presentation : FP 4 4 where
  relator := ![
    sDRelator s1Word,
    sERelator s1Word,
    sDRelator s2Word,
    sERelator s2Word
  ]

/-- The group defined by the initial four-relator Borisov presentation. -/
abbrev G0 := presentation.Group

/-- Evaluate a four-generator word in the initial Borisov presented group. -/
def evalWord (w : G0Word) : G0 := presentation.evalWord w

/-- The generator `d` in the initial presented group. -/
def d : G0 := evalWord dWord
/-- The generator `e` in the initial presented group. -/
def e : G0 := evalWord eWord
/-- The stable generator with the indicated color in the initial presented group. -/
def stable (beta : Fin 2) : G0 := evalWord (stableWord beta)

/-- `A_i = d^i F_i e^i`, with Lean's index `i` starting at zero. -/
def aWord (datum : Thue.StandingDatum) (i : Fin 3) : G0Word :=
  let exponent := i.val + 1
  Word.product
    [Word.pow dWord exponent, positiveWord (datum.F i), Word.pow eWord exponent]

/-- `B_i = d^i E_i e^i`, with Lean's index `i` starting at zero. -/
def bWord (datum : Thue.StandingDatum) (i : Fin 3) : G0Word :=
  let exponent := i.val + 1
  Word.product
    [Word.pow dWord exponent, positiveWord (datum.E i), Word.pow eWord exponent]

/-- The evaluated left rewriting-rule word in the initial presented group. -/
def a (datum : Thue.StandingDatum) (i : Fin 3) : G0 :=
  evalWord (aWord datum i)

/-- The evaluated right rewriting-rule word in the initial presented group. -/
def b (datum : Thue.StandingDatum) (i : Fin 3) : G0 :=
  evalWord (bWord datum i)

/-- Indices for the displayed bases `s1,s2,A1,A2,A3` and
`s1,s2,B1,B2,B3`. -/
abbrev Basis := Fin 2 ⊕ Fin 3

/-- The two stable generators and three left rewriting-rule generators. -/
def uBasis (datum : Thue.StandingDatum) : Basis → G0
  | .inl beta => stable beta
  | .inr i => a datum i

/-- The two stable generators and three right rewriting-rule generators. -/
def vBasis (datum : Thue.StandingDatum) : Basis → G0
  | .inl beta => stable beta
  | .inr i => b datum i

/-- The base subgroup `<d,e>`. -/
def DE : Subgroup G0 :=
  Subgroup.closure ({d, e} : Set G0)

/-- `J_beta = <d,e,s_beta>`. -/
def J (beta : Fin 2) : Subgroup G0 :=
  Subgroup.closure ({d, e, stable beta} : Set G0)

/-- The cyclic subgroup generated by the selected stable generator. -/
def stableCyclic (beta : Fin 2) : Subgroup G0 :=
  Subgroup.closure ({stable beta} : Set G0)

/-- `U_c = <s1,s2,A1,A2,A3>`. -/
def Uc (datum : Thue.StandingDatum) : Subgroup G0 :=
  Subgroup.closure (Set.range (uBasis datum))

/-- `V_c = <s1,s2,B1,B2,B3>`. -/
def Vc (datum : Thue.StandingDatum) : Subgroup G0 :=
  Subgroup.closure (Set.range (vBasis datum))

theorem uBasis_mem_Uc (datum : Thue.StandingDatum) (q : Basis) :
    uBasis datum q ∈ Uc datum :=
  Subgroup.subset_closure ⟨q, rfl⟩

theorem vBasis_mem_Vc (datum : Thue.StandingDatum) (q : Basis) :
    vBasis datum q ∈ Vc datum :=
  Subgroup.subset_closure ⟨q, rfl⟩

theorem stable_mem_J (beta : Fin 2) : stable beta ∈ J beta := by
  apply Subgroup.subset_closure
  simp

/-- Formal content of Borisov's Assertion IV used by the paper: both
displayed generating lists are free bases, and the letterwise correspondence
extends to the stated subgroup isomorphism. -/
structure AssertionIV (datum : Thue.StandingDatum) : Prop where
  u_free : Function.Injective (FreeGroup.lift (uBasis datum))
  v_free : Function.Injective (FreeGroup.lift (vBasis datum))
  correspondence : ∃ equiv : Uc datum ≃* Vc datum,
    ∀ q : Basis,
      (equiv ⟨uBasis datum q, uBasis_mem_Uc datum q⟩ : G0) = vBasis datum q

/-- A basis factor literally uses a stable letter.  A stable basis factor
uses its own index; an `A_i` or `B_i` factor uses both indices because every
`F_i` and `E_i` contains both letters. -/
def UsesStable (w : FreeGroup Basis) (gamma : Fin 2) : Prop :=
  ∃ letter ∈ w.toWord,
    match letter.1 with
    | .inl beta => beta = gamma
    | .inr _ => True

/-- The exact normal-form consequence of Assertion V needed in
Lemma 3.5 of the paper.

Assertion IV makes `w.toWord` a minimal displayed-basis representative.
Assertion V removes every Britton pinch from its literal expansion.  Comparing
the resulting multiple-HNN normal form with a representative in `J beta` or
in `<d,e>` gives these four support exclusions. -/
structure AssertionV (datum : Thue.StandingDatum)
    (_hIV : AssertionIV datum) : Prop where
  u_mem_J : ∀ (w : FreeGroup Basis) (beta gamma : Fin 2),
    FreeGroup.lift (uBasis datum) w ∈ J beta → gamma ≠ beta →
      ¬ UsesStable w gamma
  v_mem_J : ∀ (w : FreeGroup Basis) (beta gamma : Fin 2),
    FreeGroup.lift (vBasis datum) w ∈ J beta → gamma ≠ beta →
      ¬ UsesStable w gamma
  u_mem_DE : ∀ w : FreeGroup Basis,
    FreeGroup.lift (uBasis datum) w ∈ DE →
      ∀ gamma : Fin 2, ¬ UsesStable w gamma
  v_mem_DE : ∀ w : FreeGroup Basis,
    FreeGroup.lift (vBasis datum) w ∈ DE →
      ∀ gamma : Fin 2, ¬ UsesStable w gamma

/-- Exchange the two stable-generator indices. -/
def other (beta : Fin 2) : Fin 2 :=
  if beta = 0 then 1 else 0

private theorem other_ne (beta : Fin 2) : other beta ≠ beta := by
  fin_cases beta <;> decide

private theorem letter_is_stable_of_no_other
    (w : FreeGroup Basis) (beta : Fin 2)
    (h : ∀ gamma : Fin 2, gamma ≠ beta → ¬ UsesStable w gamma)
    (letter : Basis × Bool) (hletter : letter ∈ w.toWord) :
    letter.1 = Sum.inl beta := by
  cases hq : letter.1 with
  | inl gamma =>
      by_cases hgb : gamma = beta
      · simp [hgb]
      · exact (h gamma hgb ⟨letter, hletter, by simp [hq]⟩).elim
  | inr i =>
      exact
        (h (other beta) (other_ne beta)
          ⟨letter, hletter, by simp [hq]⟩).elim

private theorem toWord_eq_nil_of_no_stable
    (w : FreeGroup Basis)
    (h : ∀ gamma : Fin 2, ¬ UsesStable w gamma) :
    w.toWord = [] := by
  cases hw : w.toWord with
  | nil => rfl
  | cons letter tail =>
      have hletter : letter ∈ w.toWord := by simp [hw]
      cases hq : letter.1 with
      | inl gamma => exact (h gamma ⟨letter, hletter, by simp [hq]⟩).elim
      | inr i => exact (h 0 ⟨letter, hletter, by simp [hq]⟩).elim

private theorem freeGroup_eq_one_of_no_stable
    (w : FreeGroup Basis)
    (h : ∀ gamma : Fin 2, ¬ UsesStable w gamma) : w = 1 := by
  rw [← FreeGroup.mk_toWord (x := w), toWord_eq_nil_of_no_stable w h]
  rfl

private theorem lift_mk_mem_stableCyclic
    (basis : Basis → G0) (beta : Fin 2) (letters : List (Basis × Bool))
    (hletters : ∀ letter ∈ letters, letter.1 = Sum.inl beta) :
    FreeGroup.lift basis (FreeGroup.mk letters) ∈
      Subgroup.closure ({basis (Sum.inl beta)} : Set G0) := by
  let C := Subgroup.closure ({basis (Sum.inl beta)} : Set G0)
  have hgen : basis (Sum.inl beta) ∈ C := by
    apply Subgroup.subset_closure
    simp
  induction letters with
  | nil => exact C.one_mem
  | cons letter tail ih =>
      rcases letter with ⟨q, sign⟩
      have hq : q = Sum.inl beta := hletters (q, sign) (by simp)
      subst q
      have iht : FreeGroup.lift basis (FreeGroup.mk tail) ∈ C :=
        ih (by
          intro letter hletter
          exact hletters letter (List.mem_cons_of_mem _ hletter))
      cases sign
      · simpa [C] using C.mul_mem (C.inv_mem hgen) iht
      · simpa [C] using C.mul_mem hgen iht

private theorem lift_mem_stableCyclic
    (basis : Basis → G0) (w : FreeGroup Basis) (beta : Fin 2)
    (h : ∀ gamma : Fin 2, gamma ≠ beta → ¬ UsesStable w gamma) :
    FreeGroup.lift basis w ∈
      Subgroup.closure ({basis (Sum.inl beta)} : Set G0) := by
  rw [← FreeGroup.mk_toWord (x := w)]
  apply lift_mk_mem_stableCyclic basis beta w.toWord
  intro letter hletter
  exact letter_is_stable_of_no_other w beta h letter hletter

private theorem stableCyclic_le_Uc (datum : Thue.StandingDatum)
    (beta : Fin 2) : stableCyclic beta ≤ Uc datum := by
  unfold stableCyclic
  rw [Subgroup.closure_le]
  intro g hg
  rw [Set.mem_singleton_iff] at hg
  subst g
  exact uBasis_mem_Uc datum (Sum.inl beta)

private theorem stableCyclic_le_Vc (datum : Thue.StandingDatum)
    (beta : Fin 2) : stableCyclic beta ≤ Vc datum := by
  unfold stableCyclic
  rw [Subgroup.closure_le]
  intro g hg
  rw [Set.mem_singleton_iff] at hg
  subst g
  exact vBasis_mem_Vc datum (Sum.inl beta)

private theorem stableCyclic_le_J (beta : Fin 2) :
    stableCyclic beta ≤ J beta := by
  unfold stableCyclic
  rw [Subgroup.closure_le]
  intro g hg
  rw [Set.mem_singleton_iff] at hg
  subst g
  exact stable_mem_J beta

/-- First half of Lemma 3.5 of the paper: `U_c ∩ J_beta = <s_beta>`. -/
theorem Uc_inf_J (datum : Thue.StandingDatum) (beta : Fin 2)
    (hIV : AssertionIV datum) (hV : AssertionV datum hIV) :
    Uc datum ⊓ J beta = stableCyclic beta := by
  apply le_antisymm
  · intro g hg
    have hgU := hg.1
    change g ∈ Subgroup.closure (Set.range (uBasis datum)) at hgU
    rw [← FreeGroup.range_lift_eq_closure] at hgU
    rcases hgU with ⟨w, rfl⟩
    exact lift_mem_stableCyclic (uBasis datum) w beta
      (fun gamma hne => hV.u_mem_J w beta gamma hg.2 hne)
  · intro g hg
    exact ⟨stableCyclic_le_Uc datum beta hg, stableCyclic_le_J beta hg⟩

/-- First half of Lemma 3.5 of the paper: `V_c ∩ J_beta = <s_beta>`. -/
theorem Vc_inf_J (datum : Thue.StandingDatum) (beta : Fin 2)
    (hIV : AssertionIV datum) (hV : AssertionV datum hIV) :
    Vc datum ⊓ J beta = stableCyclic beta := by
  apply le_antisymm
  · intro g hg
    have hgV := hg.1
    change g ∈ Subgroup.closure (Set.range (vBasis datum)) at hgV
    rw [← FreeGroup.range_lift_eq_closure] at hgV
    rcases hgV with ⟨w, rfl⟩
    exact lift_mem_stableCyclic (vBasis datum) w beta
      (fun gamma hne => hV.v_mem_J w beta gamma hg.2 hne)
  · intro g hg
    exact ⟨stableCyclic_le_Vc datum beta hg, stableCyclic_le_J beta hg⟩

/-- Second half of Lemma 3.5 of the paper: `U_c ∩ <d,e> = 1`. -/
theorem Uc_inf_DE (datum : Thue.StandingDatum)
    (hIV : AssertionIV datum) (hV : AssertionV datum hIV) :
    Uc datum ⊓ DE = ⊥ := by
  apply le_antisymm
  · intro g hg
    have hgU := hg.1
    change g ∈ Subgroup.closure (Set.range (uBasis datum)) at hgU
    rw [← FreeGroup.range_lift_eq_closure] at hgU
    rcases hgU with ⟨w, rfl⟩
    have hw : w = 1 := freeGroup_eq_one_of_no_stable w (hV.u_mem_DE w hg.2)
    subst w
    simp
  · exact bot_le

/-- Second half of Lemma 3.5 of the paper: `V_c ∩ <d,e> = 1`. -/
theorem Vc_inf_DE (datum : Thue.StandingDatum)
    (hIV : AssertionIV datum) (hV : AssertionV datum hIV) :
    Vc datum ⊓ DE = ⊥ := by
  apply le_antisymm
  · intro g hg
    have hgV := hg.1
    change g ∈ Subgroup.closure (Set.range (vBasis datum)) at hgV
    rw [← FreeGroup.range_lift_eq_closure] at hgV
    rcases hgV with ⟨w, rfl⟩
    have hw : w = 1 := freeGroup_eq_one_of_no_stable w (hV.v_mem_DE w hg.2)
    subst w
    simp
  · exact bot_le

/-- The four intersections in Lemma 3.5 of the paper, bundled together. -/
theorem lemma4_2 (datum : Thue.StandingDatum)
    (hIV : AssertionIV datum) (hV : AssertionV datum hIV) :
    (∀ beta : Fin 2,
      Uc datum ⊓ J beta = stableCyclic beta ∧
      Vc datum ⊓ J beta = stableCyclic beta) ∧
    Uc datum ⊓ DE = ⊥ ∧ Vc datum ⊓ DE = ⊥ := by
  refine ⟨?_, Uc_inf_DE datum hIV hV, Vc_inf_DE datum hIV hV⟩
  intro beta
  exact ⟨Uc_inf_J datum beta hIV hV, Vc_inf_J datum beta hIV hV⟩

end BorisovIntersections
end Undecidability
