/-
Copyright (c) 2026 Scott Armstrong, Vlad Vicol. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Vlad Vicol
-/
module

public import LeanPool.CaffarelliKohnNirenberg.Leray.FourierMildNonlinearity

/-!
# The nonlinear regularized mild equation

The tensor in the Stokes integral is the regularized velocity tensor from
`eq:reg-mild`.
-/

public section

noncomputable section

namespace CKN.Leray

/-- The tensor trajectory generated by a velocity trajectory in
`eq:reg-mild`. -/
@[expose]
def regularizedMildTensorTrajectory (ρ : RegMollifierProfile) (ε : ℝ)
    (hε : 0 < ε) (u : ℝ → RealVectorL2) : ℝ → RealTensorL2 :=
  fun t => regularizedMildTensor ρ ε hε (u t)

/-- A trajectory solves the nonlinear regularized mild equation
`eq:reg-mild` with initial datum `b`. -/
@[expose]
def SatisfiesRegularizedMildVelocityEquation (ρ : RegMollifierProfile)
    (ε : ℝ) (hε : 0 < ε) (b : RealVectorL2) (u : ℝ → RealVectorL2) : Prop :=
  SatisfiesRegularizedMildEquation b u (regularizedMildTensorTrajectory ρ ε hε u)

end CKN.Leray

end
