/-
Copyright (c) 2026 Qiuyu Ren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Marc Kegel, Shana Yunsheng Li, Qiuyu Ren
-/

module

public import LeanPool.SmallUndecidableGroups.Computability
public import Mathlib.Data.Fin.VecNotation

/-!
# Core

Part of the dependency closure of the small undecidable group constructions.
-/

@[expose] public section

namespace Undecidability

/-- A finite-word Thue system, regarded as a symmetric rewriting system. -/
abbrev ThueSystem (α : Type*) :=
  Set (List α × List α)

/-- One application of a Thue rule in an arbitrary two-sided context. -/
def ThueStep {α : Type*}
    (T : ThueSystem α) (u v : List α) : Prop :=
  ∃ l r x y : List α,
    (x, y) ∈ T ∧
      ((u = l ++ x ++ r ∧ v = l ++ y ++ r) ∨
       (u = l ++ y ++ r ∧ v = l ++ x ++ r))

/-- Equality generated by finitely many Thue rewrites. -/
def ThueEq {α : Type*} (T : ThueSystem α) :=
  Relation.ReflTransGen (ThueStep T)

namespace Thue

theorem thueStep_symm {T : ThueSystem α} {X Y : List α}
    (h : ThueStep T X Y) : ThueStep T Y X := by
  rcases h with ⟨l, r, x, y, hxy, hwords⟩
  rcases hwords with ⟨hX, hY⟩ | ⟨hX, hY⟩
  · exact ⟨l, r, x, y, hxy, Or.inr ⟨hY, hX⟩⟩
  · exact ⟨l, r, x, y, hxy, Or.inl ⟨hY, hX⟩⟩

theorem thueEq_symm {T : ThueSystem α} {X Y : List α}
    (h : ThueEq T X Y) : ThueEq T Y X := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih =>
      exact (Relation.ReflTransGen.single (thueStep_symm hstep)).trans ih

theorem thueStep_context {T : ThueSystem α} (l r : List α)
    {X Y : List α} (h : ThueStep T X Y) :
    ThueStep T (l ++ X ++ r) (l ++ Y ++ r) := by
  rcases h with ⟨l', r', x, y, hxy, hwords⟩
  rcases hwords with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · exact ⟨l ++ l', r' ++ r, x, y, hxy,
      Or.inl ⟨by simp only [List.append_assoc], by simp only [List.append_assoc]⟩⟩
  · exact ⟨l ++ l', r' ++ r, x, y, hxy,
      Or.inr ⟨by simp only [List.append_assoc], by simp only [List.append_assoc]⟩⟩

theorem thueEq_context {T : ThueSystem α} (l r : List α)
    {X Y : List α} (h : ThueEq T X Y) :
    ThueEq T (l ++ X ++ r) (l ++ Y ++ r) :=
  h.lift (fun W ↦ l ++ W ++ r)
    (fun _ _ hstep ↦ thueStep_context l r hstep)

/-- The three left sides before applying the synchronizing code. -/
def baseF (U₃ : List (Fin 2)) : Fin 3 → List (Fin 2) :=
  ![
    [(0 : Fin 2), 0, 1, 0, 1],
    [(0 : Fin 2), 0, 1, 1],
    U₃
  ]

/-- The three right sides before applying the synchronizing code. -/
def baseE (V₃ : List (Fin 2)) : Fin 3 → List (Fin 2) :=
  ![
    [(1 : Fin 2), 0, 0],
    [(1 : Fin 2), 0, 0],
    V₃
  ]

/-- The binary three-rule Thue system parametrized by its long left and right words. -/
def baseSystem (U₃ V₃ : List (Fin 2)) : ThueSystem (Fin 2) :=
  Set.range fun i => (baseF U₃ i, baseE V₃ i)

end Thue
end Undecidability
